### PR TITLE
VE-80: Remove warnings from modal component

### PR DESCRIPTION
**Pull request by falco953**
## What

- Remove invalid nesting on story for modal component
- Add Modal.Heading as source for aria label of the Dialog content
- lowercase maxWidth prop since its not a recognized property by React

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)

### CODE REVIEW

**Review by sirJiggles — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: all files reviewed, 1 unresolved discussion (waiting on @falco953)

___
*[package.json, line 4 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo7zol5DdPV8v9hqk6n:-Mo7zol5DdPV8v9hqk6o:b-7ipetz) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/package.json#L4)):*
> ```JSON
>   "name": "@qualifyze/design-system",
>   "description": "Qualifyze Design System",
>   "version": "1.4.5",
> ```

sir, this package is using changeset, if you remove this, add a changeset then after merge you can do changeset release

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
Thanks for the PR! :partying_face:  A11y PRs are always very welcome!

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220#-:-Mo85aZP5dqjnUczXfXW:bbn45hc)* status: all files reviewed, 3 unresolved discussions (waiting on @falco953 and @sirJiggles)

___
*[package.json, line 4 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo7zol5DdPV8v9hqk6n:-Mo85i7o2tLknK4UPr29:bxpq1le) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/package.json#L4)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

sir, this package is using changeset, if you remove this, add a changeset then after merge you can do changeset release
</blockquote></details>

+1

More specifically, you can remove this change and then run `npx changeset` and go from there. This will add the necessary file you can commit with this PR.
___
*[src/components/Modal/index.jsx, line 19 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo85tSb0VR7UGBhM8YH:-Mo85tSb0VR7UGBhM8YI:bqydhfn) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/src/components/Modal/index.jsx#L19)):*
> ```JavaScript
> const Heading = ({ children }) => (
>   <Box sx={{ px: 3, pt: 3, pb: 3, mr: '44px' }}>
>     <BaseHeading as="span" level={4} weight="weak" id="heading_modal">
> ```

Very nice! However, a single id won't suffice if we have several modals. We need to have a way to make this unique to _this_ very modal. I believe this could be achieved with something like this: https://react-spectrum.adobe.com/react-aria/useId.html

In then newest React version, there will be something out of the box for this but sadly not in the one we're using currently.
___
*[src/components/Modal/index.jsx, line 79 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo86LQkElzd2ptET236:-Mo86LQkElzd2ptET237:bfys6b5) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/src/components/Modal/index.jsx#L79)):*
> ```JavaScript
>         }}
>       >
>         <DialogContent maxwidth={maxWidth} aria-labelledby="heading_modal">
> ```

The `maxWidth` -> `maxwidth` is great intention but it's not quite what we want. It's not a breaking issue, though, so I will mark as non-blocking. The warning tells you that `maxWidth` (`max-width`) will not be passed to the DOM. Which is exactly what we want! So actually ignoring this warning would be correct here. Changing it to `maxwidth` means this will appear in the DOM, which is unnecessary.

If you really want to get rid of the warning, then you'd have to filter out the prop before passing it to the `BaseDialog`. I haven't tried this but I believe it would look like this:

```
const DialogContent = styled(BaseDialogContent, {
  shouldForwardProp: p => p !== 'maxWidth',
})(props => {
  return {
    '&[data-reach-dialog-content]': {
      width: `100%`,
      margin: 0,
      padding: 0,
      background: `white`,
      position: `relative`,
      marginTop: props.theme.space[6],
      [`@media (min-width: ${props.theme.breakpoints.small})`]: {
        borderRadius: props.theme.radii[2],
        maxWidth: props.theme.sizes[props.maxWidth],
        marginBottom: props.theme.space[5],
      },
    },
  }
})

```

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: all files reviewed, 3 unresolved discussions (waiting on @falco953 and @sirJiggles)

___
*[src/components/Modal/index.jsx, line 19 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo85tSb0VR7UGBhM8YH:-Mo8DQPm-uzmHKfByXL5:bbu7spw) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/src/components/Modal/index.jsx#L19)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Very nice! However, a single id won't suffice if we have several modals. We need to have a way to make this unique to _this_ very modal. I believe this could be achieved with something like this: https://react-spectrum.adobe.com/react-aria/useId.html

In then newest React version, there will be something out of the box for this but sadly not in the one we're using currently.
</blockquote></details>

Thinking about it again, not quite sure how this would ideally look at first glance, so if you think `useId` is the wrong way to go then you're probably right :sweat_smile:

**Review by falco953 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @falco953, @gregoralbrecht, and @sirJiggles)

___
*[src/components/Modal/index.jsx, line 19 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo85tSb0VR7UGBhM8YH:-Mo8Qd3X4myNQ1JLDSro:bk54ak1) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/src/components/Modal/index.jsx#L19)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Thinking about it again, not quite sure how this would ideally look at first glance, so if you think `useId` is the wrong way to go then you're probably right :sweat_smile: 
</blockquote></details>

mmh yes, valid point. What about using a context for the modal? For now this includes just the id, but this way every modal has its unique id
___
*[src/components/Modal/index.jsx, line 79 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo86LQkElzd2ptET236:-Mo8S9_J9GV8AcPv1xYF:b-lvo3ut) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/src/components/Modal/index.jsx#L79)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The `maxWidth` -> `maxwidth` is great intention but it's not quite what we want. It's not a breaking issue, though, so I will mark as non-blocking. The warning tells you that `maxWidth` (`max-width`) will not be passed to the DOM. Which is exactly what we want! So actually ignoring this warning would be correct here. Changing it to `maxwidth` means this will appear in the DOM, which is unnecessary.

If you really want to get rid of the warning, then you'd have to filter out the prop before passing it to the `BaseDialog`. I haven't tried this but I believe it would look like this:

```
const DialogContent = styled(BaseDialogContent, {
  shouldForwardProp: p => p !== 'maxWidth',
})(props => {
  return {
    '&[data-reach-dialog-content]': {
      width: `100%`,
      margin: 0,
      padding: 0,
      background: `white`,
      position: `relative`,
      marginTop: props.theme.space[6],
      [`@media (min-width: ${props.theme.breakpoints.small})`]: {
        borderRadius: props.theme.radii[2],
        maxWidth: props.theme.sizes[props.maxWidth],
        marginBottom: props.theme.space[5],
      },
    },
  }
})

```
</blockquote></details>

Thanks you, works perfectly well 😊 done 😊 
___
*[package.json, line 4 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo7zol5DdPV8v9hqk6n:-Mo8QW0_8fjI1b9HxVAv:b-q9ko9c) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/package.json#L4)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

+1

More specifically, you can remove this change and then run `npx changeset` and go from there. This will add the necessary file you can commit with this PR.
</blockquote></details>

Ah sorry, didn't know that, have reverted it and used changes

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @falco953, @gregoralbrecht, and @sirJiggles)

___
*[src/components/Modal/index.jsx, line 19 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo85tSb0VR7UGBhM8YH:-Mo8azS1Enkhgj9envZH:bbuyxgd) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/src/components/Modal/index.jsx#L19)):*
<details><summary><i>Previously, falco953 (Falco Trompeter) wrote…</i></summary><blockquote>

mmh yes, valid point. What about using a context for the modal? For now this includes just the id, but this way every modal has its unique id
</blockquote></details>

I don't think we need to reach for context :thinking: There are two separate concerns here, right?

1. Have a unique ID
2. Pass this ID to both heading and dialog content

For 1, doesn't matter what we do, `useId` would still work nicely.

For 2, context is an option but might be overkill. Currently, we're just passing `{children}` down, but we could also iterate over them and add the necessary prop to `Modal.Heading` directly. You could use `React.cloneElement` for instance: Map over the children and if it's a heading you clone it pass the id as a prop

**Review by sirJiggles — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: all files reviewed, 2 unresolved discussions (waiting on @falco953 and @gregoralbrecht)

**Review by falco953 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht and @sirJiggles)

___
*[src/components/Modal/index.jsx, line 19 at r1](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo85tSb0VR7UGBhM8YH:-Mo97qZgAAn8fyJmytEP:b-1uqphq) ([raw file](https://github.com/qualifyze/design-system/blob/b52f697d7275d19379a301278a772fc0b845861a/src/components/Modal/index.jsx#L19)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I don't think we need to reach for context :thinking: There are two separate concerns here, right?

1. Have a unique ID
2. Pass this ID to both heading and dialog content

For 1, doesn't matter what we do, `useId` would still work nicely.

For 2, context is an option but might be overkill. Currently, we're just passing `{children}` down, but we could also iterate over them and add the necessary prop to `Modal.Heading` directly. You could use `React.cloneElement` for instance: Map over the children and if it's a heading you clone it pass the id as a prop
</blockquote></details>

Yes, you are right, thats probably simpler. Done

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: all files reviewed, 3 unresolved discussions (waiting on @falco953 and @sirJiggles)

___
*[src/components/Modal/index.jsx, line 111 at r4](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo9OO_OC0ZJG5rXcntS:-Mo9OO_OC0ZJG5rXcntT:b-m5y7wf) ([raw file](https://github.com/qualifyze/design-system/blob/18823fa1ed0e0c643024c66d837c5ae2a6a24791/src/components/Modal/index.jsx#L111)):*
> ```JavaScript
>             <Icon name="cross" size="large" />
>           </Box>
>           {React.Children.map(children, child => {
> ```

This breaks the "bare modal" story probably because there are no child nodes
___
*[src/components/Modal/index.jsx, line 117 at r4](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo9OUCfDmrENeEDiwmN:-Mo9OUCfDmrENeEDiwmO:b-r8cfy7) ([raw file](https://github.com/qualifyze/design-system/blob/18823fa1ed0e0c643024c66d837c5ae2a6a24791/src/components/Modal/index.jsx#L117)):*
> ```JavaScript
>               return React.cloneElement(child, { id: headingId })
>             }
>             return React.cloneElement(child)
> ```

If I'm not mistaken, we don't need to clone children that remain unchanged 
___
*[src/components/Modal/index.jsx, line 119 at r4](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo9OE6J1HHbpC7AbL1M:-Mo9OE6J1HHbpC7AbL1N:b-2lo1s6) ([raw file](https://github.com/qualifyze/design-system/blob/18823fa1ed0e0c643024c66d837c5ae2a6a24791/src/components/Modal/index.jsx#L119)):*
> ```JavaScript
>             return React.cloneElement(child)
>           })}
>           {children}
> ```

This means we'll render all children twice

**Review by falco953 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @gregoralbrecht and @sirJiggles)

___
*[src/components/Modal/index.jsx, line 111 at r4](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo9OO_OC0ZJG5rXcntS:-MoCvxi39hw4TDIGajRW:bqicwqs) ([raw file](https://github.com/qualifyze/design-system/blob/18823fa1ed0e0c643024c66d837c5ae2a6a24791/src/components/Modal/index.jsx#L111)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This breaks the "bare modal" story probably because there are no child nodes
</blockquote></details>

Oh yes 😀 Didn't thought on that, thanks, fixed
___
*[src/components/Modal/index.jsx, line 117 at r4](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo9OUCfDmrENeEDiwmN:-MoCvvi07b1FD7H8Z8EE:b-wi3vi0) ([raw file](https://github.com/qualifyze/design-system/blob/18823fa1ed0e0c643024c66d837c5ae2a6a24791/src/components/Modal/index.jsx#L117)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

If I'm not mistaken, we don't need to clone children that remain unchanged 
</blockquote></details>

Yes, thats right, done
___
*[src/components/Modal/index.jsx, line 119 at r4](https://reviewable.io/reviews/qualifyze/design-system/220#-Mo9OE6J1HHbpC7AbL1M:-MoCw-Lq1BuIXHsE7thU:b-i2d4cp) ([raw file](https://github.com/qualifyze/design-system/blob/18823fa1ed0e0c643024c66d837c5ae2a6a24791/src/components/Modal/index.jsx#L119)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This means we'll render all children twice
</blockquote></details>

I must have been asleep 😁 Removed

**Review by gregoralbrecht — APPROVED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @sirJiggles)

**Review by sirJiggles — APPROVED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/220)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @falco953)

**Pull request merged**
