### PR TITLE
Introduce Tabs using Radix UI.

### PR DESCRIPTION
**Pull request by jorgechiapello**
# What❓
Added a Tabs component.

# Why 💁‍♀️

For VE-119 we would like to introduce a new Tabs component and overall we don't have a Tabs component in our new DS.

# How to test ✅

Run locally with Storybook and go to "Tabs", there are two stories showing the components (and sub-components).

# What was tested / affected 📝

Affects no one so far.

### CODE REVIEW

**Comment by gsuess** [comment]
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245)

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
Love this PR :heart_eyes: Thank you! :100: 

This kind of component can be quite tricky to implement, so IMHO our main goal with this PR should be to make it work with basic use cases and worry about more complex ones later when we need to.

> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245#-:-MplHXKM1qA6chxduyBd:beznoo4)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @jorgechiapello and @pablosci)

___
*[.changeset/thick-rice-judge.md, line 2 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplHb_LEFSiwmkYrM0d:-MplHb_LEFSiwmkYrM0e:bhe30v8) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/.changeset/thick-rice-judge.md#L2)):*
> ```Markdown
> ---
> '@qualifyze/design-system': patch
> ```

I think this should be a `minor` because it's a new feature
___
*[src/components/Tabs/index.jsx, line 15 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplJsYe8nOS3AlBTV1a:-MplJsYf6u2QQa75tmvr:b-e55u7) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L15)):*
> ```JavaScript
>     paddingLeft: props.theme.space[props.paddingX] ?? 0,
>     paddingRight: props.theme.space[props.paddingX] ?? 0,
>     margin: `0 ${props.theme.space[props.space ?? 3]}px`,
> ```

I think I get what you're trying to do here (make the spacing adjustable) but I'm not sure this is the right API for it. `space` usually refers to spacing values in our theme and this one just means "space in pixels". Do we really need to make this flexible? At first glance, it seems perfectly fine to have a specific spacing set for all tabs? Same goes for `paddingX` 
___
*[src/components/Tabs/index.jsx, line 20 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplJWZJ8D4-JcGsqtji:-MplJWZJ8D4-JcGsqtjj:b-r4joh7) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L20)):*
> ```JavaScript
> 
> const TabTrigger = styled(TabsPrimitives.Trigger)(props => ({
>   'color': props.theme.colors.grey[600],
> ```

Only `grey.800` and `grey.900` have sufficient contrast on white
___
*[src/components/Tabs/index.jsx, line 34 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplImxa6yCnMAE33FJk:-MplImxa6yCnMAE33FJl:beimz6v) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L34)):*
> ```JavaScript
>     color: props.theme.colors.grey[700],
>   },
>   '&:focus': {
> ```

Seems like it's currently using browser default focus styles. I think we should add our custom focus ring here (it's a box shadow in the theme)


___
*[src/components/Tabs/index.jsx, line 46 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplKHUi3Zf4WUsiVjWt:-MplKHUi3Zf4WUsiVjWu:bfe8ukz) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L46)):*
> ```JavaScript
> Tabs.displayName = 'Tabs'
> 
> export { Tabs, TabList, TabContent, TabTrigger }
> ```

I suggest we also export the `TabsPrimitive` as we do with, for instance, `DropdownMenu`. This way, consumers could potentially build their own tabs if the styling in here doesn't suit their use case.
___
*[src/components/Tabs/index.stories.jsx, line 38 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplKfx1EfPOxdP1QOR5:-MplKfx1EfPOxdP1QOR6:b5kgdie) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.stories.jsx#L38)):*
> ```JavaScript
>           The reasons are:
>         </Text>
>         <Text>- keep all items consistent</Text>
> ```

Do you know we have a `List` component for lists? :nerd_face: 
___
*[src/components/Tabs/index.stories.jsx, line 63 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplKs7g1SFo2LkC342z:-MplKs7g1SFo2LkC343-:bpfdgaq) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.stories.jsx#L63)):*
> ```JavaScript
> }
> 
> export const WithOverview = () => {
> ```

Thank you for including two stories including docs! Maybe we should link to the Radix UI docs in addition?
___
*[src/components/Tabs/index.stories.jsx, line 63 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplL6L3E8QApMnrnyPE:-MplL6L3E8QApMnrnyPF:bt1y9nw) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.stories.jsx#L63)):*
> ```JavaScript
> }
> 
> export const WithOverview = () => {
> ```

I'd love to see an example of how we would build what's in the Figma mockups here:


Especially the gray border because I think this would be a great test for whether this component achieves what we want to have. The specific question I have is: Do we need to include the border in this component or is this something the consumer will decide to add? Do we have more example use cases than this single mockup? cc @pablosci

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @jorgechiapello and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMaNc7BmaXFJH45X7:-MplMaNd7F2RMFq8Oi03:bm5o7dr) (no related file):*
One more use case we should think about: What if the tabs are too big for the viewport? Does the tab list scroll?

---
___
*[src/components/Tabs/index.jsx, line 41 at r2](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMqLAEbSK_wV7kK1K:-MplMqLAEbSK_wV7kK1L:b-brufn6) ([raw file](https://github.com/qualifyze/design-system/blob/d90331be57cd024a5a98c9aa0b103c6b428a6dc7/src/components/Tabs/index.jsx#L41)):*
> ```JavaScript
> 
> const TabContent = styled(TabsPrimitives.Content)(() => ({
>   outline: 'none',
> ```

Please don't remove the outline without providing a different visual. In this case, you can add the `focusRing` box-shadow

**Review by jorgechiapello — COMMENTED** [review]
Makes sense.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245#-:-MplknxNAJrVz39IQC0b:b-dxcbts)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @gregoralbrecht and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMaNc7BmaXFJH45X7:-Mplkffd7IdlY-kdYcMd:b-6e6cy9) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

One more use case we should think about: What if the tabs are too big for the viewport? Does the tab list scroll?
</blockquote></details>

I just added the scroll on the X axis. I liked how  they did it in [Carbon with a carets](https://react.carbondesignsystem.com/?path=/story/components-tabs--default) on the sides for scrolling the TabList but it was too complex for me to implement quickly.

---
___
*[src/components/Tabs/index.jsx, line 15 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplJsYe8nOS3AlBTV1a:-MplRi8R3cDZ5OgMsTqd:bql9msm) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L15)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I think I get what you're trying to do here (make the spacing adjustable) but I'm not sure this is the right API for it. `space` usually refers to spacing values in our theme and this one just means "space in pixels". Do we really need to make this flexible? At first glance, it seems perfectly fine to have a specific spacing set for all tabs? Same goes for `paddingX` 
</blockquote></details>

Good points. Let's remove them and see if by a more clear frame we can avoid them. My fear was more about this sort of disalignment case that would force outside content to use padding but if we can avoid this extra props, the better.
___
*[src/components/Tabs/index.jsx, line 20 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplJWZJ8D4-JcGsqtji:-MplWCqk-xFPVrYU670m:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L20)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Only `grey.800` and `grey.900` have sufficient contrast on white
</blockquote></details>

Done.
___
*[src/components/Tabs/index.jsx, line 34 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplImxa6yCnMAE33FJk:-MplX3pk0sSbC1mnbpwl:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L34)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Seems like it's currently using browser default focus styles. I think we should add our custom focus ring here (it's a box shadow in the theme)



</blockquote></details>

Done.
___
*[src/components/Tabs/index.jsx, line 46 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplKHUi3Zf4WUsiVjWt:-MplXt_66k1euFzUXcXa:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L46)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I suggest we also export the `TabsPrimitive` as we do with, for instance, `DropdownMenu`. This way, consumers could potentially build their own tabs if the styling in here doesn't suit their use case.
</blockquote></details>

Done.
___
*[src/components/Tabs/index.jsx, line 41 at r2](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMqLAEbSK_wV7kK1K:-MplXswm0lt_jIWmoePp:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/d90331be57cd024a5a98c9aa0b103c6b428a6dc7/src/components/Tabs/index.jsx#L41)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Please don't remove the outline without providing a different visual. In this case, you can add the `focusRing` box-shadow
</blockquote></details>

Done.
___
*[src/components/Tabs/index.stories.jsx, line 63 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplKs7g1SFo2LkC342z:-MplXvvqDY1oR7tWu6uV:b-dxcbts) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.stories.jsx#L63)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Thank you for including two stories including docs! Maybe we should link to the Radix UI docs in addition?
</blockquote></details>

Makes sense.
___
*[src/components/Tabs/index.stories.jsx, line 63 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplL6L3E8QApMnrnyPE:-MplZOEI8uaPk2_pzzAP:b-rq7cl3) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.stories.jsx#L63)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I'd love to see an example of how we would build what's in the Figma mockups here:


Especially the gray border because I think this would be a great test for whether this component achieves what we want to have. The specific question I have is: Do we need to include the border in this component or is this something the consumer will decide to add? Do we have more example use cases than this single mockup? cc @pablosci 
</blockquote></details>

I think we should add it. I like the way it looks and doens't ruin the second example. Nice thing is that you can play a lot with the components and styling
___
*[.changeset/thick-rice-judge.md, line 2 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplHb_LEFSiwmkYrM0d:-MplRJWXCsYn3ZGb8mir:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/.changeset/thick-rice-judge.md#L2)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I think this should be a `minor` because it's a new feature
</blockquote></details>

Done.

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245)* status: all files reviewed, 1 unresolved discussion (waiting on @jorgechiapello and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMaNc7BmaXFJH45X7:-MppCI6iEp6KNou9lQAK:b-ap5e20) (no related file):*
<details><summary><i>Previously, jorgechiapello (Jorge Alberto Chiapello) wrote…</i></summary><blockquote>

I just added the scroll on the X axis. I liked how  they did it in [Carbon with a carets](https://react.carbondesignsystem.com/?path=/story/components-tabs--default) on the sides for scrolling the TabList but it was too complex for me to implement quickly.
</blockquote></details>

Yeah the carets are great, but native scrolling should be fine for now :) I haven't tested this in detail, have you? I'll approve because we can easily do this in a separate PR but would be nice if you could double-check if we can bake in support for overflow and scroll somehow.

---
___
*[src/components/Tabs/index.jsx, line 46 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplKHUi3Zf4WUsiVjWt:-MppD01s6Hc8dDHo3HCc:btq8hts) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L46)):*
<details><summary><i>Previously, jorgechiapello (Jorge Alberto Chiapello) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Tiny typo: `TabsPrimitives` and it should be `TabsPrimitive`

**Review by gregoralbrecht — COMMENTED** [review]
I just noticed we don't export the component yet, do we?

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245#-:-MppHbpk0d7YWASK2woM:b-7dybyo)* status: all files reviewed, 1 unresolved discussion (waiting on @jorgechiapello and @pablosci)

**Review by jorgechiapello — COMMENTED** [review]
No we don't, we are not following the same pattern as other components doing:
```
FileUpload.Dropzone = Dropzone
FileUpload.File = File
FileUpload.FileBox = FileBox
FileUpload.PrimaryAction = PrimaryAction
FileUpload.DangerAction = DangerAction

export default FileUpload
```
Should we follow it? In that case, I would remove the prefix `Tab` from the subcomponents.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245#-:-MppknsO-8C22ijof90K:bhwr3sf)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMaNc7BmaXFJH45X7:-MppklyH6h0TxB_sw2CH:b-80tlqk) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Yeah the carets are great, but native scrolling should be fine for now :) I haven't tested this in detail, have you? I'll approve because we can easily do this in a separate PR but would be nice if you could double-check if we can bake in support for overflow and scroll somehow.
</blockquote></details>

Sure.

---
___
*[src/components/Tabs/index.jsx, line 46 at r1](https://reviewable.io/reviews/qualifyze/design-system/245#-MplKHUi3Zf4WUsiVjWt:-Mppjysz4AvJcKGWTWNo:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/50707adddf32a43d72d5380a84dc9e1a84846ffe/src/components/Tabs/index.jsx#L46)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Tiny typo: `TabsPrimitives` and it should be `TabsPrimitive`
</blockquote></details>

Done.

**Review by gregoralbrecht — COMMENTED** [review]
Oh you're right! Didn't even see this. I'd suggest to match the naming that Radix uses:

So we can do this:
```
import { Tabs } from '@qf/ds'

<Tabs>
    <Tabs.List>
      <Tabs.Trigger />
    </Tabs.List>
    <Tabs.Content />
  </Tabs>
```

It's not 100% the same, because we don't export `Tabs.Root`, but `Tabs` instead of `Tabs.Root` should be fine.

What I meant though: We need to add it to the main exports file :)

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245#-:-Mppo0az7Mo3QdKOeByR:b-6xvwv5)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @pablosci)

**Review by jorgechiapello — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMaNc7BmaXFJH45X7:-MpqKj8G05_9AwSBa-wd:b-xexiaz) (no related file):*
<details><summary><i>Previously, jorgechiapello (Jorge Alberto Chiapello) wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

The line on the bottom of each triggers make the trigger list to overflow on the Y axis. There is no problem with that alone but the thing is that if we want the X axis to show the scrollbar, then we have to apply that too to the Y axis, which renders the scrollbar in all widths.
We can't tell the Y axis to overflow and the X axis to show the scrollbar.
This makes the line below the triggers to not be directly on top of the bottom line.
A better explanation in [here](https://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue/6433475#6433475)

---

**Review by gregoralbrecht — COMMENTED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMaNc7BmaXFJH45X7:-MpqSqPa2Ipa4Lver4hn:bfoqzed) (no related file):*
<details><summary><i>Previously, jorgechiapello (Jorge Alberto Chiapello) wrote…</i></summary><blockquote>

The line on the bottom of each triggers make the trigger list to overflow on the Y axis. There is no problem with that alone but the thing is that if we want the X axis to show the scrollbar, then we have to apply that too to the Y axis, which renders the scrollbar in all widths.
We can't tell the Y axis to overflow and the X axis to show the scrollbar.
This makes the line below the triggers to not be directly on top of the bottom line.
A better explanation in [here](https://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue/6433475#6433475)
</blockquote></details>

Okay that's definitely odd. It seems like overflow-x works totally fine in the latest deployed preview, so are we good? I saw that you removed the negative margin, this means that the borders will stack instead of overlap.

What we now have:


What we want:


The Tailwind UI examples use a slightly different markup, maybe we need to use the same if applying the border to the Tabs.List doesn't work? :thinking: 

After playing around with it I understand the issue better now, seems like if we go with the styling I added then we cannot have overflow: scroll, right? I see two options here now:

A. Not add overflow at all for now.

B. Spend more time figuring out the styling with overflow enabled.

What do you think?

---

**Review by jorgechiapello — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMaNc7BmaXFJH45X7:-MprxCKf8wqPS_32kAjd:b-hq176m) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Okay that's definitely odd. It seems like overflow-x works totally fine in the latest deployed preview, so are we good? I saw that you removed the negative margin, this means that the borders will stack instead of overlap.

What we now have:


What we want:


The Tailwind UI examples use a slightly different markup, maybe we need to use the same if applying the border to the Tabs.List doesn't work? :thinking: 

After playing around with it I understand the issue better now, seems like if we go with the styling I added then we cannot have overflow: scroll, right? I see two options here now:

A. Not add overflow at all for now.

B. Spend more time figuring out the styling with overflow enabled.

What do you think?
</blockquote></details>

I would give it a bit more tries.
I translate the line to a pseudo element and with a new position.

---

**Review by jorgechiapello — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245#-:-Mpv4o4x5BgRLx66U62M:bnfp4nl)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/245#-Mpv4olKCJ0VWw1gla86:-Mpv4olKCJ0VWw1gla87:b-j08ajg) (no related file):*
Ok, pseudo element didn't work, let's go for box-shadow. I think it is ok now.

---

**Review by gregoralbrecht — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/245)* status: all files reviewed, 1 unresolved discussion (waiting on @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/245#-MplMaNc7BmaXFJH45X7:-Mpv6C4p8T2M0AAIKOSt:bd65hcy) (no related file):*
<details><summary><i>Previously, jorgechiapello (Jorge Alberto Chiapello) wrote…</i></summary><blockquote>

I would give it a bit more tries.
I translate the line to a pseudo element and with a new position.
</blockquote></details>

Thanks for trying, though!

---

**Pull request merged**
