### PR TITLE
AppBar: adapt parent theme instead of overriding it

### PR DESCRIPTION
**Pull request by phjardas**
The AppBar uses a custom local theme with the font sizes from v2. However, this custom theme uses the default theme as the base instead of the parent theme provided by the surrounding page.

### CODE REVIEW

**Comment by gsuess** [comment]
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/320)

**Review by sirJiggles — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/320)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[`src/components/AppBar/index.jsx` line 87 at r1](https://reviewable.io/reviews/qualifyze/design-system/320#-N2QJIcc-XSpeWwxWA-B:-N2QJIcc-XSpeWwxWA-C:bwg4fax) ([raw file](https://github.com/qualifyze/design-system/blob/5f3c2006b9f17dae51e604af96c020ab4488dd63/src/components/AppBar/index.jsx#L87)):*
> ```JavaScript
> const v2fontSizes = ['12px', '14px', '16px', '18px']
> 
> function useThemeV2() {
> ```

in the story we make it so you extend the theme by passing a string of the theme version. but here for the implementation you are adding to the default theme.

I am curious what is the difference here :sweat: 

I see that we do what we used to but this time in a hook and using memo but still spreading the base theme?  

I am just a little confused by the story book I guess as in that one we show using a param to work out the theme but in this one there is no param, I guess as we don't need to, for this case at least have more than one extension to the theme?

also in the story book you define your own useTheme function but here you are calling the one from the DS. that is what is throwing me off I guess.

Maybe we could just talk about it real quick, would be faster. the tldr is I don't get what has really changed here

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/320)* status: all files reviewed, 1 unresolved discussion (waiting on @sirJiggles)

___
*[`src/components/AppBar/index.jsx` line 87 at r1](https://reviewable.io/reviews/qualifyze/design-system/320#-N2QJIcc-XSpeWwxWA-B:-N2RE54F53mew489_olO:b8cjoju) ([raw file](https://github.com/qualifyze/design-system/blob/5f3c2006b9f17dae51e604af96c020ab4488dd63/src/components/AppBar/index.jsx#L87)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

in the story we make it so you extend the theme by passing a string of the theme version. but here for the implementation you are adding to the default theme.

I am curious what is the difference here :sweat: 

I see that we do what we used to but this time in a hook and using memo but still spreading the base theme?  

I am just a little confused by the story book I guess as in that one we show using a param to work out the theme but in this one there is no param, I guess as we don't need to, for this case at least have more than one extension to the theme?

also in the story book you define your own useTheme function but here you are calling the one from the DS. that is what is throwing me off I guess.

Maybe we could just talk about it real quick, would be faster. the tldr is I don't get what has really changed here
</blockquote></details>

Imagine the following situation:

```
<ThemeProvider theme={someCustomizedTheme}>
  <AppBar />
</ThemeProvider>
```

The only thing why the app bar has its own theme provider is to customize the font sizes. However, since it uses the standard theme as the base for the customization, any theme provided by the outside component is simply ignored. Let's say you want the whole page to use pink instead of blue as the primary color, then the app bar would still be rendered in blue, because its theme is based on the default theme instead of the parent theme.

I've fixed this by basing the app bar's custom theme on the parent theme instead of the default theme.

In the story I'm simply simulating this behavior by supplying different base themes using the knob.

**Review by sirJiggles — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phjardas)

___
*[`src/components/AppBar/index.jsx` line 87 at r1](https://reviewable.io/reviews/qualifyze/design-system/320#-N2QJIcc-XSpeWwxWA-B:-N2ROkkpDrJxzvlK8-J-:b-jzhl0y) ([raw file](https://github.com/qualifyze/design-system/blob/5f3c2006b9f17dae51e604af96c020ab4488dd63/src/components/AppBar/index.jsx#L87)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Imagine the following situation:

```
<ThemeProvider theme={someCustomizedTheme}>
  <AppBar />
</ThemeProvider>
```

The only thing why the app bar has its own theme provider is to customize the font sizes. However, since it uses the standard theme as the base for the customization, any theme provided by the outside component is simply ignored. Let's say you want the whole page to use pink instead of blue as the primary color, then the app bar would still be rendered in blue, because its theme is based on the default theme instead of the parent theme.

I've fixed this by basing the app bar's custom theme on the parent theme instead of the default theme.

In the story I'm simply simulating this behavior by supplying different base themes using the knob.
</blockquote></details>

I see! thanks for the explanation, I guess that is what useTheme from the DS does then!

**Pull request merged**
