### PR TITLE
Fixes for new branding theme

### PR DESCRIPTION
**Pull request by phjardas**
A few small fixes for the new branding theme:

* Use grey instead of pink as the secondary color. ➡️ [Storybook](https://design-system-git-v2-fixes2-qualifyze.vercel.app/?path=/story/button--default) (change the color with knobs)
* Remove the color `grey[50]` which was accidentally introduced in #332.
* Fix color of focus ring. ➡️ [Storybook](https://design-system-git-v2-fixes2-qualifyze.vercel.app/?path=/story/form--default)
* Set background color to white.
* Fix font weight of bold elements inside of Text. ➡️ [Storybook](https://design-system-git-v2-fixes2-qualifyze.vercel.app/?path=/story/text--default)

### CODE REVIEW

**Comment by gsuess** [comment]
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/334)

**Review by vubogovich — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/334)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[`src/util/style/theme.js` line 48 at r1](https://reviewable.io/reviews/qualifyze/design-system/334#-NBRNsqW5uN5LFL_D0s0:-NBRNsqW5uN5LFL_D0s1:b-1h89o) ([raw file](https://github.com/qualifyze/design-system/blob/d2e44bf62c00a49dd0687db231acc03e45c0e111/src/util/style/theme.js#L48)):*
> ```JavaScript
>   },
>   grey: {
>     50: 'hsl(220, 20%, 97%)',
> ```

This was interesting inconsistency and it would be nice to reflect some context in PR desc and changelog! And definitely mention it's a potential breaking change :wink: though I could not find any usage in our code base so no push for `major` release.

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/334)* status: all files reviewed, 1 unresolved discussion (waiting on @vubogovich)

___
*[`src/util/style/theme.js` line 48 at r1](https://reviewable.io/reviews/qualifyze/design-system/334#-NBRNsqW5uN5LFL_D0s0:-NBRPEW4BhXD1LGPMp5V:b-7vh9ch) ([raw file](https://github.com/qualifyze/design-system/blob/d2e44bf62c00a49dd0687db231acc03e45c0e111/src/util/style/theme.js#L48)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

This was interesting inconsistency and it would be nice to reflect some context in PR desc and changelog! And definitely mention it's a potential breaking change :wink: though I could not find any usage in our code base so no push for `major` release.
</blockquote></details>

That color was accidentally introduced yesterday in https://github.com/Qualifyze/design-system/pull/332/files#diff-bfec1adb785179eff20a9a075d532f32059c2a9de10caacf6e7e20f396423143R48 -- and yes, nobody is using it yet.

**Review by vubogovich — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/334)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[`src/util/style/theme.js` line 48 at r1](https://reviewable.io/reviews/qualifyze/design-system/334#-NBRNsqW5uN5LFL_D0s0:-NBRPb__9PND3OrQWv9y:b1n0sln) ([raw file](https://github.com/qualifyze/design-system/blob/d2e44bf62c00a49dd0687db231acc03e45c0e111/src/util/style/theme.js#L48)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

That color was accidentally introduced yesterday in https://github.com/Qualifyze/design-system/pull/332/files#diff-bfec1adb785179eff20a9a075d532f32059c2a9de10caacf6e7e20f396423143R48 -- and yes, nobody is using it yet.
</blockquote></details>

In changelog please <3

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/334)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @vubogovich)

___
*[`src/util/style/theme.js` line 48 at r1](https://reviewable.io/reviews/qualifyze/design-system/334#-NBRNsqW5uN5LFL_D0s0:-NBRR3V72EeQCloIW4WM:br0bztg) ([raw file](https://github.com/qualifyze/design-system/blob/d2e44bf62c00a49dd0687db231acc03e45c0e111/src/util/style/theme.js#L48)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

In changelog please <3
</blockquote></details>

Better now?

**Review by vubogovich — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/334)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phjardas)

___
*[`src/util/style/theme.js` line 48 at r1](https://reviewable.io/reviews/qualifyze/design-system/334#-NBRNsqW5uN5LFL_D0s0:-NBRRKzOB0_Xo_hAaFWU:b-9755fn) ([raw file](https://github.com/qualifyze/design-system/blob/d2e44bf62c00a49dd0687db231acc03e45c0e111/src/util/style/theme.js#L48)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Better now?
</blockquote></details>

Thank you!

**Pull request merged**
