### PR TITLE
Use Changesets for releases

### PR DESCRIPTION
**Pull request by gregoralbrecht**
We're currently using two distinct release processes: A manual one for `main` and Changesets for `next`. In order to not have that cognitive overhead, let's align them.

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/142)

### CODE REVIEW

**Review by vubogovich — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/142)* status: all files reviewed, 6 unresolved discussions (waiting on @gregoralbrecht)

___
*[package.json, line 31 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-Mgoeu_D7s7G4goZW91I:-Mgoeu_EDtPRNYi3CHeF:b-ph6vnk) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/package.json#L31)):*
> ```JSON
>     "lint": "npm run lint:scripts && npm run lint:styles",
>     "test": "jest",
>     "release": "changeset publish"
> ```

I think this should include at least `npm run build` before publish, otherwise the published version will not have any artifacts from `dist`.
___
*[.github/workflows/node.yml, line 4 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-MgodYhO5x6Zj56iIbl7:-MgodYhO5x6Zj56iIbl8:b3mxa2y) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/.github/workflows/node.yml#L4)):*
> ```YAML
> 
> on:
>   push:
> ```

Webstorm complains here as string or object is expected. Solved with `push: {}`.
___
*[.github/workflows/node.yml, line 10 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-MgodNBc8gnRknohOibB:-MgodNBc8gnRknohOibC:brmg4wv) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/.github/workflows/node.yml#L10)):*
> ```YAML
>   pull_request:
>     branches:
>       - next
> ```

The branch should be `main` here.
___
*[.github/workflows/node.yml, line 29 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-Mgodk6v6oYa3pPLh5Zu:-Mgodk6v6oYa3pPLh5Zv:b91jpva) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/.github/workflows/node.yml#L29)):*
> ```YAML
>           node-version: ${{ matrix.node-version }}
> 
>       - name: Cache dependencies
> ```

This step can be replaced with `cache: npm` parameter for `setup-node` step - see https://github.com/Qualifyze/airtable/blob/main/.github/workflows/test.yml
___
*[.github/workflows/node.yml, line 43 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-MgoeDMj9_HELWCTijtl:-MgoeDMj9_HELWCTijtm:b-dibvtj) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/.github/workflows/node.yml#L43)):*
> ```YAML
>           npm ci
> 
>       - name: Build and test
> ```

Lint step is missing from the previous workflow.
Also as an idea we could add the check that no unexpected artifacts at the end:
```
      - name: Check integrity of repository artifacts
        uses: Qualifyze/check-git-integrity-action@v1.0.0
```
___
*[.github/workflows/release.yml, line 25 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-Mgoec-R6P_kNr7o89LE:-Mgoec-R6P_kNr7o89LF:b-ehw6js) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/.github/workflows/release.yml#L25)):*
> ```YAML
> 
>       - name: Install dependencies
>         run: npm install
> ```

`npm ci` is faster. Also nice to add `cache: npm` in `setup-node` to get dependencies cached (see similar comment for node.yml).

**Review by vubogovich — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/142)* status: all files reviewed, 7 unresolved discussions (waiting on @gregoralbrecht)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/142#-MgofZxV5fOctyHyP-_L:-MgofZxV5fOctyHyP-_M:bbktfsz) (no related file):*
Surprisingly the test check was not reported while the workflow is run. I guess it might be related to the strategy since it added the postfix to the job name `test (14.x)`.
Once it's fixed, we might come to the problem that both `test` workflows are running (for main and for next) on every push which might unblock PR with a wrong check (i.e. PR is raised to `main` but `next` test is successful.

---

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/142)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @vubogovich)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/142#-MgofZxV5fOctyHyP-_L:-MgolXpN41F_cU58xq0L:b9r9ib5) (no related file):*
There is no `test` check, this is coming from `dev-infrastructure`. We'll need to rename the required checks manually in this repo, which should be fine. The thing is: AFAICT, `dev-infra` doesn't support having different checks for different branches, so we will probably not be able to cover this with IaC and instead we'll need to do it manually. This is fine for now, I think we're going to find a different solution in the future, e.g., by splitting this up into two repos.

>Once it's fixed, we might come to the problem that both test workflows are running (for main and for next) on every push which might unblock PR with a wrong check (i.e. PR is raised to main but next test is successful.

Hm let's just try it out and find out what happens :)

---
___
*[package.json, line 31 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-Mgoeu_D7s7G4goZW91I:-MgpSdT-ChHKVhaWjoON:b1htqiv) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/package.json#L31)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

I think this should include at least `npm run build` before publish, otherwise the published version will not have any artifacts from `dist`.
</blockquote></details>

I added a `prerelease` script to make sure it's built and tested before publishing
___
*[.github/workflows/node.yml, line 10 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-MgodNBc8gnRknohOibB:-MgpSr6dBDnULpnZLYkS:b-kl8g4c) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/.github/workflows/node.yml#L10)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

The branch should be `main` here.
</blockquote></details>

good catch!
___
*[.github/workflows/node.yml, line 29 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-Mgodk6v6oYa3pPLh5Zu:-MgpTPOm8J1raA6s5TQu:bcyd8zn) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/.github/workflows/node.yml#L29)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

This step can be replaced with `cache: npm` parameter for `setup-node` step - see https://github.com/Qualifyze/airtable/blob/main/.github/workflows/test.yml
</blockquote></details>

Nice! Done
___
*[.github/workflows/node.yml, line 43 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-MgoeDMj9_HELWCTijtl:-MgpTaqb2eDeR58sfx7K:b-8b11j9) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/.github/workflows/node.yml#L43)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Lint step is missing from the previous workflow.
Also as an idea we could add the check that no unexpected artifacts at the end:
```
      - name: Check integrity of repository artifacts
        uses: Qualifyze/check-git-integrity-action@v1.0.0
```
</blockquote></details>

Added
___
*[.github/workflows/release.yml, line 25 at r1](https://reviewable.io/reviews/qualifyze/design-system/142#-Mgoec-R6P_kNr7o89LE:-MgpUMd65hggDD-X0dX5:bb6un1j) ([raw file](https://github.com/qualifyze/design-system/blob/0f52ae8e7dfb615f4ee95a659e31b2dbc561591e/.github/workflows/release.yml#L25)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

`npm ci` is faster. Also nice to add `cache: npm` in `setup-node` to get dependencies cached (see similar comment for node.yml).
</blockquote></details>

Done

**Review by vubogovich — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/142)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/142#-MgofZxV5fOctyHyP-_L:-Mgpj6AV5CuD0AmceKna:bdrlgv3) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

There is no `test` check, this is coming from `dev-infrastructure`. We'll need to rename the required checks manually in this repo, which should be fine. The thing is: AFAICT, `dev-infra` doesn't support having different checks for different branches, so we will probably not be able to cover this with IaC and instead we'll need to do it manually. This is fine for now, I think we're going to find a different solution in the future, e.g., by splitting this up into two repos.

>Once it's fixed, we might come to the problem that both test workflows are running (for main and for next) on every push which might unblock PR with a wrong check (i.e. PR is raised to main but next test is successful.

Hm let's just try it out and find out what happens :)
</blockquote></details>

You say it's fine to rename the required check because you have the admin access to github repo :)
I say it's not fine as I don't have the access but the latter is actually a good motivation to do IaC ;)
If `dev-infra` does not support it, maybe it's a good moment to introduce it there. Or split repo into two, or whatever but please no manual changes to the infra as we agreed to do IaC.
Regarding the required check for the main branch of design-system, it can be and should be configured in `dev-infra`. However, the problem here is not the current name `test` which is very clear. I think the problem is `test (14.x)` for the current workflow.


---

**Review by vubogovich — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregoralbrecht)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/142#-MgofZxV5fOctyHyP-_L:-MgqD9mI1QGdspRk5s73:b-2miw92) (no related file):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

You say it's fine to rename the required check because you have the admin access to github repo :)
I say it's not fine as I don't have the access but the latter is actually a good motivation to do IaC ;)
If `dev-infra` does not support it, maybe it's a good moment to introduce it there. Or split repo into two, or whatever but please no manual changes to the infra as we agreed to do IaC.
Regarding the required check for the main branch of design-system, it can be and should be configured in `dev-infra`. However, the problem here is not the current name `test` which is very clear. I think the problem is `test (14.x)` for the current workflow.


</blockquote></details>

I guess PR Qualifyze/dev-infrastructure#186 to rename the required check to `test (14.x)` resolves this discussion.

---

**Pull request merged**
