### PR TITLE
QC-1181: Add select field creatable component

### PR DESCRIPTION
**Pull request by sirJiggles**
For the what, why how and where please have a look at https://github.com/qualifyze/design-system/pull/102 this is just a break down of that PR

here we are just adding one of the 4 components, in this case the clearable select

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/110)

### CODE REVIEW

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/110)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @gregoralbrecht and @sirJiggles)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAF3zD6397WPTxsMRe:-MgAF3zD6397WPTxsMRf:b4ent0y) (no related file):*
From a UX perspective, I'd love to make the "Create new option" option stand out a bit more so it's clear what's happening. Let me talk to Pablo about this because I don't know how this might look like yet.

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAIHTLA3vkzAzu924j:-MgAIHTLA3vkzAzu924k:b-eiek4l) (no related file):*
When I do the following, the placeholder isn't shown anymore and I wonder why that is (because it works for `SelectField`):

1. Select a movie
2. Navigate to a different story in Storybook
3. Navigate back to `SelectCreatableField`

I feel like this might be solved if we address the other issues (how to store state, etc.)

---
___
*[src/components/index.js, line 32 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgA7JMI-IPIMWUgfeXB:-MgA7JMI-IPIMWUgfeXC:b-jacrok) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/index.js#L32)):*
> ```JavaScript
> export { default as Rect } from './Rect'
> export { default as SelectField } from './SelectField'
> export { default as SelectFieldCreatable } from './SelectFieldCreatable'
> ```

We add the suffix`Field` whenever something is connected to Formik, i.e., should be used inside a form. In this case this would mean then name is `SelectCreatableField`. Let me know if I should rename this before merging, though! I didn't catch it before, sorry.
___
*[src/components/SelectFieldCreatable/baseTheme.js, line 3 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgA87iiASOGxgA7DNk_:-MgA87iiASOGxgA7DNka:bck4zgt) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/baseTheme.js#L3)):*
> ```JavaScript
> import { theme } from '../../util/style'
> 
> export default {
> ```

This is the stuff we can deduplicate, because the duplication gives us hardly any value. I see how this comment is confusing af after I said duplication doesn't hurt and it's not a blocking thing. We can tackle this later :)
___
*[src/components/SelectFieldCreatable/index.jsx, line 124 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAGpFhB1VzSMBGFfH4:-MgAGpFhB1VzSMBGFfH5:b-ot1d2p) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/index.jsx#L124)):*
> ```JavaScript
>   indicatorSeparator: () => ({ display: 'none' }),
> }
> const SelectFieldCreatable = ({
> ```

Currently, this renders again each time I type a character, which doesn't happen with `SelectField`. Let's try to avoid that, I will look into why it does that. Not necessarily blocking but if it's easy to avoid then we should do that
___
*[src/components/SelectFieldCreatable/index.jsx, line 134 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgACOwcEUJPolMTqCiI:-MgACOwcEUJPolMTqCiJ:b-eg9fwh) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/index.jsx#L134)):*
> ```JavaScript
> }) => {
>   const [field, meta, helpers] = useField({ name })
>   const [customInput, setCustomInput] = useState('')
> ```

At first glance, this worries me a bit because it means we store state in two separate places: Formik state and this state here. I see some comments further down but I'm not sure I follow why we need a separate state?
___
*[src/components/SelectFieldCreatable/index.jsx, line 149 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAFJxfEFI1QbLCJFpJ:-MgAFJxfEFI1QbLCJFpK:b-m3u24z) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/index.jsx#L149)):*
> ```JavaScript
>           // if the user would like to add a new value
>           if (actionMeta?.action === 'set-value') {
>             options.push({
> ```

This mutates the options we pass to the component, which is something we should avoid imho. This goes hand in hand with the above question about why we need to store this anywhere outside of Formik state

**Review by pablosci — CHANGES_REQUESTED** [review]
I'm getting a weird error here: if you select an item in this component it creates an empty one at the bottom of the list, x empty items per x times you selected one
Screenshot 2021-08-03 at 09 45 52
Screenshot 2021-08-03 at 09 46 04

**Review by sirJiggles — COMMENTED** [review]
This issue should be resolved @pablosci 

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/110#-:-MgAU7Ot9X4lNVZDBOXg:bp5newf)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @gregoralbrecht and @pablosci)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAIHTLA3vkzAzu924j:-MgATRf3C362pOKD3InE:b93pfl3) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

When I do the following, the placeholder isn't shown anymore and I wonder why that is (because it works for `SelectField`):

1. Select a movie
2. Navigate to a different story in Storybook
3. Navigate back to `SelectCreatableField`

I feel like this might be solved if we address the other issues (how to store state, etc.)
</blockquote></details>

Hmm for me select field does not preserve the state of the selection when going form select to another story. Is this something we need to be worried about? would it mean that when used on a page the state would not be preserved for the user on coming back to the form?

I would imagine at least that this would be expected if the component is removed from the dom and even more if we have some custom selections that the user provides. 

I had a [quick look](https://stackoverflow.com/questions/63624474/how-to-persist-formik-form-values-if-navigate-to-other-screen-in-react-native) and there seem to be libs to support this kind of functionality for formik but I am not sure if it is something out of the box

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAF3zD6397WPTxsMRe:-MgAUA6B0vPLoWsg3Awq:bqud5v2) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

From a UX perspective, I'd love to make the "Create new option" option stand out a bit more so it's clear what's happening. Let me talk to Pablo about this because I don't know how this might look like yet.
</blockquote></details>

@pablosci would you like me to make some changes to the text for "Create new XXX" option item?

---
___
*[src/components/index.js, line 32 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgA7JMI-IPIMWUgfeXB:-MgAM0TA2nZrB6hkKG9K:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/index.js#L32)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

We add the suffix`Field` whenever something is connected to Formik, i.e., should be used inside a form. In this case this would mean then name is `SelectCreatableField`. Let me know if I should rename this before merging, though! I didn't catch it before, sorry.
</blockquote></details>

Done.
___
*[src/components/SelectFieldCreatable/baseTheme.js, line 3 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgA87iiASOGxgA7DNk_:-MgAM45U4dsbfuzcH6me:bc52im2) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/baseTheme.js#L3)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This is the stuff we can deduplicate, because the duplication gives us hardly any value. I see how this comment is confusing af after I said duplication doesn't hurt and it's not a blocking thing. We can tackle this later :)
</blockquote></details>

Yeah I duplicated it all as we have separate folders now for each component and it seemed wrong to make a 'shared select' folder for these files. I can do it for sure though if you would be ok with that
___
*[src/components/SelectFieldCreatable/index.jsx, line 124 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAGpFhB1VzSMBGFfH4:-MgASeOb60Tulo0YJgLR:b-csfpao) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/index.jsx#L124)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Currently, this renders again each time I type a character, which doesn't happen with `SelectField`. Let's try to avoid that, I will look into why it does that. Not necessarily blocking but if it's easy to avoid then we should do that
</blockquote></details>

Hmm, my guess would be that it needs to re-render down to the fact it changes the list of items with this new "create new" option. I did not do anything special here just the out of the box example. I will have a little look now too though to see if I can / need to stop this
___
*[src/components/SelectFieldCreatable/index.jsx, line 134 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgACOwcEUJPolMTqCiI:-MgANwiIDpRpNjK7SwG2:b-6df3kr) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/index.jsx#L134)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

At first glance, this worries me a bit because it means we store state in two separate places: Formik state and this state here. I see some comments further down but I'm not sure I follow why we need a separate state?
</blockquote></details>

I am not too hot on formik to be honest, I had a look and these 'options' and the field value are different things with different state from what I can see. One seems to be the options the form could choose from and the other is the actual values that it has and the state for the selection. Maybe I am missing some other way to do this, as there are to me three things here:

- default options from the props
- any other options the user might provide (this state is used for that)
- the state of the form field (currently selected option)

Maybe we can have a call on this if that is ok, I have also changed it a little now also as per the comment below but the principle is still the same.
___
*[src/components/SelectFieldCreatable/index.jsx, line 149 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAFJxfEFI1QbLCJFpJ:-MgAOgZu1tehR7y_gLZ2:b76uxv5) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/index.jsx#L149)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This mutates the options we pass to the component, which is something we should avoid imho. This goes hand in hand with the above question about why we need to store this anywhere outside of Formik state
</blockquote></details>

I have made a new array with state that gets the initial value of the props passed in, then mutates it. let me know if that is cool.

**Review by pablosci — APPROVED** [review]
thanks for the fixes! works very good 👏

**Review by gregoralbrecht — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r4, 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/110#-:-MgFGoB_3nERe-j35Skd:bnfp4nl)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @gregoralbrecht)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAIHTLA3vkzAzu924j:-MgFGJluAcDCEaCQrscV:b-vzbtpv) (no related file):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

Hmm for me select field does not preserve the state of the selection when going form select to another story. Is this something we need to be worried about? would it mean that when used on a page the state would not be preserved for the user on coming back to the form?

I would imagine at least that this would be expected if the component is removed from the dom and even more if we have some custom selections that the user provides. 

I had a [quick look](https://stackoverflow.com/questions/63624474/how-to-persist-formik-form-values-if-navigate-to-other-screen-in-react-native) and there seem to be libs to support this kind of functionality for formik but I am not sure if it is something out of the box
</blockquote></details>

The _placeholder_, not the value. This was a bug, it's fixed now

---
___
*[src/components/SelectFieldCreatable/baseTheme.js, line 3 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgA87iiASOGxgA7DNk_:-MgFGRNp6NZOtx3tvvDn:b-a44php) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/baseTheme.js#L3)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

Yeah I duplicated it all as we have separate folders now for each component and it seemed wrong to make a 'shared select' folder for these files. I can do it for sure though if you would be ok with that
</blockquote></details>

I'm totally okay with it and I think we should do it, but not necessarily in this PR. We can keep the files in `SelectField` and export them from there
___
*[src/components/SelectFieldCreatable/index.jsx, line 124 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgAGpFhB1VzSMBGFfH4:-MgFGcgl1lIozevE6X5i:b-r98nzv) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/index.jsx#L124)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

Hmm, my guess would be that it needs to re-render down to the fact it changes the list of items with this new "create new" option. I did not do anything special here just the out of the box example. I will have a little look now too though to see if I can / need to stop this
</blockquote></details>

I wasn't able to bring the number of renders down too much either, so yeah let's leave it 
___
*[src/components/SelectFieldCreatable/index.jsx, line 134 at r2](https://reviewable.io/reviews/qualifyze/design-system/110#-MgACOwcEUJPolMTqCiI:-MgFGjs3-4dxA5_hL_R5:b6yxpi2) ([raw file](https://github.com/qualifyze/design-system/blob/3026070e4a6dc5f6fce74d923266bb06f6bd0051/src/components/SelectFieldCreatable/index.jsx#L134)):*
<details><summary><i>Previously, sirJiggles (Gareth Fuller) wrote…</i></summary><blockquote>

I am not too hot on formik to be honest, I had a look and these 'options' and the field value are different things with different state from what I can see. One seems to be the options the form could choose from and the other is the actual values that it has and the state for the selection. Maybe I am missing some other way to do this, as there are to me three things here:

- default options from the props
- any other options the user might provide (this state is used for that)
- the state of the form field (currently selected option)

Maybe we can have a call on this if that is ok, I have also changed it a little now also as per the comment below but the principle is still the same.

</blockquote></details>

Resolved in a call :)

**Review by gregoralbrecht — APPROVED** [review]
> Reviewed 2 of 7 files at r4, 2 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sirJiggles)

**Review by sirJiggles — COMMENTED** [review]
> Reviewed 3 of 7 files at r4, 2 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sirJiggles)

**Pull request merged**
