### PR TITLE
Export tools, bump version to 1.0.1

### PR DESCRIPTION
**Pull request by phjardas**
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/43)

### CODE REVIEW

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/43)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[src/index.js, line 1 at r1](https://reviewable.io/reviews/qualifyze/design-system/43#-Md1CwZ45S6Jeno8GKBB:-Md1CwZ45S6Jeno8GKBC:b-9hqug4) ([raw file](https://github.com/qualifyze/design-system/blob/30068c62f038d6714d4e50e21dc782d43dc126ab/src/index.js#L1)):*
> ```JavaScript
> export * from './components'
> ```

Can we use the exports listed in the root `index.js`? Not all components under `/components were meant to be exported`. Same goes for `util/style`

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/43)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @phjardas)

___
*[src/index.js, line 1 at r1](https://reviewable.io/reviews/qualifyze/design-system/43#-Md1CwZ45S6Jeno8GKBB:-Md1hv4l1NbapxwZmzy5:b9nyyy) ([raw file](https://github.com/qualifyze/design-system/blob/30068c62f038d6714d4e50e21dc782d43dc126ab/src/index.js#L1)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Can we use the exports listed in the root `index.js`? Not all components under `/components were meant to be exported`. Same goes for `util/style`
</blockquote></details>

Abso-friggin-lutely. Better now?

**Review by gregoralbrecht — APPROVED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/43)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

**Review by gregoralbrecht — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phjardas)

**Pull request merged**
