### PR TITLE
Add `size` workflow

### PR DESCRIPTION
**Pull request by gregoralbrecht**
This PR adds a workflow that builds the target branch and compares the build for each PR in terms of bundle size. This way we can easily see if we're adding big things to our bundle before merging a PR.

This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/98)

### CODE REVIEW

**Review by vubogovich — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/98)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @gregoralbrecht)

___
*[.github/workflows/size.yml, line 12 at r1](https://reviewable.io/reviews/qualifyze/design-system/98#-Mf3K8bS-zohKfc0C_Q0:-Mf3K8bS-zohKfc0C_Q1:b-hbcsrr) ([raw file](https://github.com/qualifyze/design-system/blob/762f86a56043e14b9923fea6bba20fa632a4ac54/.github/workflows/size.yml#L12)):*
> ```YAML
>       - uses: actions/checkout@v2
>         with:
>           fetch-depth: 1
> ```

This might be omit as the default value.
___
*[.github/workflows/size.yml, line 13 at r1](https://reviewable.io/reviews/qualifyze/design-system/98#-Mf3M6Ya5IoWsHDkgsPE:-Mf3M6Ya5IoWsHDkgsPF:bivccp3) ([raw file](https://github.com/qualifyze/design-system/blob/762f86a56043e14b9923fea6bba20fa632a4ac54/.github/workflows/size.yml#L13)):*
> ```YAML
>         with:
>           fetch-depth: 1
>       - uses: preactjs/compressed-size-action@v2
> ```

Do we trust preactjs? If not, let's reference with the full commit SHA:
https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
___
*[.github/workflows/size.yml, line 15 at r1](https://reviewable.io/reviews/qualifyze/design-system/98#-Mf3KQkC0QQuDIzR4L2e:-Mf3KQkC0QQuDIzR4L2f:b-hbcsrr) ([raw file](https://github.com/qualifyze/design-system/blob/762f86a56043e14b9923fea6bba20fa632a4ac54/.github/workflows/size.yml#L15)):*
> ```YAML
>       - uses: preactjs/compressed-size-action@v2
>         with:
>           repo-token: '${{ secrets.GITHUB_TOKEN }}'
> ```

This might be omit as the default value.

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/98)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @gregoralbrecht and @vubogovich)

___
*[.github/workflows/size.yml, line 12 at r1](https://reviewable.io/reviews/qualifyze/design-system/98#-Mf3K8bS-zohKfc0C_Q0:-Mg7EAEt86G69MaWjhUG:b-3ns9jg) ([raw file](https://github.com/qualifyze/design-system/blob/762f86a56043e14b9923fea6bba20fa632a4ac54/.github/workflows/size.yml#L12)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

This might be omit as the default value.
</blockquote></details>

True! I removed it
___
*[.github/workflows/size.yml, line 13 at r1](https://reviewable.io/reviews/qualifyze/design-system/98#-Mf3M6Ya5IoWsHDkgsPE:-Mg7ETKY9TERbVfJxEQg:b-ymnl7b) ([raw file](https://github.com/qualifyze/design-system/blob/762f86a56043e14b9923fea6bba20fa632a4ac54/.github/workflows/size.yml#L13)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

Do we trust preactjs? If not, let's reference with the full commit SHA:
https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
</blockquote></details>

I'd say we do, but I still added the hash just to be sure
___
*[.github/workflows/size.yml, line 15 at r1](https://reviewable.io/reviews/qualifyze/design-system/98#-Mf3KQkC0QQuDIzR4L2e:-Mg7EW2N2pSdLrKTx8G1:bv0jxi0) ([raw file](https://github.com/qualifyze/design-system/blob/762f86a56043e14b9923fea6bba20fa632a4ac54/.github/workflows/size.yml#L15)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

This might be omit as the default value.
</blockquote></details>

True, done!

**Review by vubogovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/98)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[.changeset/sixty-pens-change.md, line 2 at r2](https://reviewable.io/reviews/qualifyze/design-system/98#-Mg7Zino7doI1eIozG11:-Mg7Zino7doI1eIozG12:b-k6nwtz) ([raw file](https://github.com/qualifyze/design-system/blob/9d2cc410e336d23a2f2f1a765f9129a0efb429ef/.changeset/sixty-pens-change.md#L2)):*
> ```Markdown
> ---
> '@qualifyze/design-system-v2': major
> ```

I think it was just a demo, do we need to merge this file?

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/98)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @vubogovich)

___
*[.changeset/sixty-pens-change.md, line 2 at r2](https://reviewable.io/reviews/qualifyze/design-system/98#-Mg7Zino7doI1eIozG11:-MgBKfq9DXQLMr0c4d18:b-lhlg8s) ([raw file](https://github.com/qualifyze/design-system/blob/9d2cc410e336d23a2f2f1a765f9129a0efb429ef/.changeset/sixty-pens-change.md#L2)):*
<details><summary><i>Previously, vubogovich (Vladimir Ubogovich) wrote…</i></summary><blockquote>

I think it was just a demo, do we need to merge this file?
</blockquote></details>

Oh how embarrassing :see_no_evil: I didn't want to commit this file, my bad

**Review by vubogovich — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/98)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregoralbrecht)

**Pull request merged**
