### PR TITLE
Improve layout for modals and sidebars (QC-1883)

### PR DESCRIPTION
**Pull request by phjardas**
# What❓

Improved the layout of the sidebar and dialog component:
* The actions of the sidebar are now always at the bottom of the screen.
* On small screens the sidebar behaves exactly like a regular dialog.
* On small screens all dialogs are now displayed full-screen.
* Better scrolling behavior for long content: the header and actions now stay fixed and only the content scrolls.
* The dialog actions are now always inlined, even on small screens.

# Screenshots

## Dialog on desktop

dialog-short-desktop
dialog-long-desktop

## Dialog on mobile

dialog-short-mobile
dialog-long-mobile

## Sidebar on desktop

sidebar-short-desktop
sidebar-long-desktop

## Sidebar on mobile

sidebar-long-mobile

### CODE REVIEW

**Comment by gsuess** [comment]
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
Thank you for the PR! :100: 

I don't feel strongly about these, but let me add my 2 cents on three bullet points:

> The actions of the sidebar are now always at the bottom of the screen.

I don't understand the intention behind that. I'd personally aim to have these things as close together as possible instead of far apart, so I'm surprised to see that.

> The dialog actions are now always inlined, even on small screens.

Ideally, this would be aligned with `<Actions>`. Historically, we wanted to make the buttons full-width on small screens, because having the left-aligned looked weird. I don't care either way really, just pointing it out.

> On small screens all dialogs are now displayed full-screen.

What's the goal here? Is this just a design choice or am I missing something? Personally, I'd prefer the bottom-aligned ones because they are way less intrusive.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284#-:-MznxXK610gstLJoJ3tK:bbc7wo8)* status: all files reviewed, 4 unresolved discussions (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwSFg6y4rvmEiTn5x:-MznwSFg6y4rvmEiTn5y:bbnma52) (no related file):*
The story with a select inside the modal is broken: 


---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwflZBMd60IHuWDlr:-MznwflZBMd60IHuWDls:b-609l4v) (no related file):*
The styling is broken on small screens, when there's not enough height:


---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznwys072MYR0FDMP_V:-Mznwys072MYR0FDMP_W:b5g5cbw) (no related file):*
I like the idea of making the header fixed for very long content. Fixing the actions, however, might be confusing. In this example, it's not obvious there's more content below: 


Having the buttons right there might be tempting to just click them without reading everything else first.

---
___
*[src/components/Modal/index.jsx, line 57 at r1](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznvxew40J7UnjEkcfK:-Mznvxew40J7UnjEkcfL:b-xoq56e) ([raw file](https://github.com/qualifyze/design-system/blob/b1c316f4e17c900f34f54bb99042708df02cbe36/src/components/Modal/index.jsx#L57)):*
> ```JavaScript
>           top: 0,
>           position: 'fixed',
>           height: '100vh',
> ```

Has this been tested on Safari? Not sure if this is still current but `vh` had some issues if I remember correctly.

**Review by phjardas — COMMENTED** [review]
Having the actions at the bottom in the sidebar variant was specified in the design scribbles by @pablosci.

I found it looking weird if the dialogs appear full-width bottom-aligned on small screens but have this margin at the top. However, I don't care too much either. :-)

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284#-:-Mzo2pK-EOShwvXkpwGl:bejp7yz)* status: all files reviewed, 4 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwSFg6y4rvmEiTn5x:-Mzo1ugj2CqSI3RqtgKh:b-b82zm9) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The story with a select inside the modal is broken: 


</blockquote></details>

Oopsie, will fix.

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwflZBMd60IHuWDlr:-Mzo1yGw-Ql-7hoG-iVa:b-xrj1t2) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The styling is broken on small screens, when there's not enough height:


</blockquote></details>

What kind of screen is that!? :laughing: Should we decide to not have fixed buttons but scroll them with the content should fix this implicitly.

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznwys072MYR0FDMP_V:-Mzo2a2j6YnOQv6CDG6N:b-676rr4) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I like the idea of making the header fixed for very long content. Fixing the actions, however, might be confusing. In this example, it's not obvious there's more content below: 


Having the buttons right there might be tempting to just click them without reading everything else first.
</blockquote></details>

Why is there no scrollbar? Is this some Mac UI magic? :roll_eyes: I agree, it may be a good idea not to fixate the buttons but scroll them with the content.

---
___
*[src/components/Modal/index.jsx, line 57 at r1](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznvxew40J7UnjEkcfK:-Mzo2jbPBvoEQ4_WjoJk:biwdnoh) ([raw file](https://github.com/qualifyze/design-system/blob/b1c316f4e17c900f34f54bb99042708df02cbe36/src/components/Modal/index.jsx#L57)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Has this been tested on Safari? Not sure if this is still current but `vh` had some issues if I remember correctly.
</blockquote></details>

Nope, will do. Alas, `100%` should suffice here...

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: all files reviewed, 4 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznwys072MYR0FDMP_V:-MzoNqkz2gtw41tBn4Ss:b-w1bcwg) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Why is there no scrollbar? Is this some Mac UI magic? :roll_eyes: I agree, it may be a good idea not to fixate the buttons but scroll them with the content.
</blockquote></details>

I've tried moving the buttons inside the scrollable container. However, the Reach Dialog automatically focusses the first interactive element, which in this case is the submit button. Hence the browser will automatically scroll to the bottom of the dialog.

There's a property `initialFocusRef`, however, I couldn't find a way to _disable_ this functionality by passing `null` or `false`. If I pass a falsy value, it always defaults to the first interactive element.

See https://reach.tech/dialog/#dialog-initialfocusref

@gregoralbrecht do you have any idea how we could solve this? I could try to refactor the component to use the [Radix Dialog](https://www.radix-ui.com/docs/primitives/components/dialog) instead, which has a cancellable event handler for the focus event.

---

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: all files reviewed, 4 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznwys072MYR0FDMP_V:-MzoQS3f5YS8Lj2HvB5P:b-q2oxxt) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

I've tried moving the buttons inside the scrollable container. However, the Reach Dialog automatically focusses the first interactive element, which in this case is the submit button. Hence the browser will automatically scroll to the bottom of the dialog.

There's a property `initialFocusRef`, however, I couldn't find a way to _disable_ this functionality by passing `null` or `false`. If I pass a falsy value, it always defaults to the first interactive element.

See https://reach.tech/dialog/#dialog-initialfocusref

@gregoralbrecht do you have any idea how we could solve this? I could try to refactor the component to use the [Radix Dialog](https://www.radix-ui.com/docs/primitives/components/dialog) instead, which has a cancellable event handler for the focus event.
</blockquote></details>

Forget about Radix, because that would introduce a breaking change, because it requires you to include the dialog and the trigger together in a dialog context. We would have to refactor all usages. :-(

---

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: all files reviewed, 4 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznwys072MYR0FDMP_V:-MzoeJw962K5tFns1BOh:bkqre63) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Forget about Radix, because that would introduce a breaking change, because it requires you to include the dialog and the trigger together in a dialog context. We would have to refactor all usages. :-(
</blockquote></details>

Yeah but Radix is probably a great idea for v2 though

---

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: all files reviewed, 4 unresolved discussions (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwflZBMd60IHuWDlr:-Mzohc0kEzOuFigb0nqN:bi2aa3i) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

What kind of screen is that!? :laughing: Should we decide to not have fixed buttons but scroll them with the content should fix this implicitly.
</blockquote></details>

Admittedly a very uncommon screen size, but shouldn't be hard to fix. I think this is due to some max-height magic or something? Not sure

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznwys072MYR0FDMP_V:-MzoiIrl8KzFbHGTII3N:b-zd696t) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Yeah but Radix is probably a great idea for v2 though
</blockquote></details>

Auto-focussing the first (focusable) element should be fine for most cases. I'm not sure if there are any specific cases in which we have a lot of text and only confirmation buttons at the bottom? I'd have expected dialogs to contain either a form or a short text with actions at the bottom. 

In case we *do* have long text and just actions at the bottom, we could put focus on the close button? 

---

**Review by pablosci — COMMENTED** [review]
@phjardas quick question: why modal now has a min height? do we want empty space in there?

**Review by phjardas — COMMENTED** [review]
I've fixed it, and it doesn't anymore. ;-)

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284#-:-Mzsdx6w0me82Elgiz6A:b-lgsp63)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @gregoralbrecht)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwSFg6y4rvmEiTn5x:-Mzse0ljEcu2O8JzOoKu:b-896fix) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Oopsie, will fix.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwflZBMd60IHuWDlr:-Mzse1q49crpoGM--zla:b-ac0ckw) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Admittedly a very uncommon screen size, but shouldn't be hard to fix. I think this is due to some max-height magic or something? Not sure
</blockquote></details>

Done with the new scroll container.

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznwys072MYR0FDMP_V:-Mzse55Z3oo7GnMSOnIT:b6ah9a4) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Auto-focussing the first (focusable) element should be fine for most cases. I'm not sure if there are any specific cases in which we have a lot of text and only confirmation buttons at the bottom? I'd have expected dialogs to contain either a form or a short text with actions at the bottom. 

In case we *do* have long text and just actions at the bottom, we could put focus on the close button? 
</blockquote></details>

All right, let's do it this way.

---
___
*[src/components/Modal/index.jsx, line 57 at r1](https://reviewable.io/reviews/qualifyze/design-system/284#-Mznvxew40J7UnjEkcfK:-Mzse8Fz3fXaT3pl0ymA:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/b1c316f4e17c900f34f54bb99042708df02cbe36/src/components/Modal/index.jsx#L57)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Nope, will do. Alas, `100%` should suffice here...
</blockquote></details>

Done.

**Comment by pablosci** [comment]
@phjardas last question: now all actions are going to be inline instead of fixed on side?

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwflZBMd60IHuWDlr:-Mzt6DgI-hx2O4MPBsIW:b-qbln9w) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Done with the new scroll container.
</blockquote></details>

This isn't blocking, but IMHO this is a step back in terms of UX on smaller, admittedly less common, screen sizes. The scroll area has gotten a lot smaller and—if the screen size is really weird—it's not possible to scroll at all. 

Now: Scroll area (in red) only inside the modal.


Before: Entire view is scroll area


These are iPhone 12 in landscape orientation, so not incredibly rare. The positioning was weird before, too—there's unnecessary white space at the top.

Feel free to acknowledge and merge ahead, just wanted to point this out

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwSFg6y4rvmEiTn5x:-Mzt8kSl8MbACzSmNa6v:bdhyzzr) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The header is still blocking the modal content


---

**Review by phjardas — COMMENTED** [review]
Yes. But a Modal shouldn't have more than one primary and one secondary action anyway.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284#-:-Mzto1TMEF0tpqYWpYk8:b-m679bd)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwSFg6y4rvmEiTn5x:-MztpHJW73roUWDE3Q5o:b6w7lva) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The header is still blocking the modal content


</blockquote></details>

The problem with the select is, in my opinion, that the options popup is not rendered in a portal with absolute positioning. I'll see if I can fix that.

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwflZBMd60IHuWDlr:-Mztpa8E0KNP4I5P4h0C:b-2xb3w7) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This isn't blocking, but IMHO this is a step back in terms of UX on smaller, admittedly less common, screen sizes. The scroll area has gotten a lot smaller and—if the screen size is really weird—it's not possible to scroll at all. 

Now: Scroll area (in red) only inside the modal.


Before: Entire view is scroll area


These are iPhone 12 in landscape orientation, so not incredibly rare. The positioning was weird before, too—there's unnecessary white space at the top.

Feel free to acknowledge and merge ahead, just wanted to point this out
</blockquote></details>

Who uses iPhone 12 in landscape? :laughing: My proposition:
* Currently we have 128px margin on top and 64px at the bottom and align the dialog towards the top.
* Instead we center the dialog vertically with a margin of 10% at both top and bottom..

---

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwSFg6y4rvmEiTn5x:-MztqSPz0qtY9ZCgOvcc:brxbtd1) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

The problem with the select is, in my opinion, that the options popup is not rendered in a portal with absolute positioning. I'll see if I can fix that.
</blockquote></details>

Checking out https://react-select.com/advanced#portaling

---

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwSFg6y4rvmEiTn5x:-MztrOh47peRFj5OQ10V:b2ge8qy) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Checking out https://react-select.com/advanced#portaling
</blockquote></details>

It works nicely with a portal! This should not have any negative side effect on any implementation really...



---

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwSFg6y4rvmEiTn5x:-Mzxmf4s7QOPkJyTtOca:b12anh2) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

It works nicely with a portal! This should not have any negative side effect on any implementation really...



</blockquote></details>

Nice! Thanks for verifying :pray: 

---
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/284#-MznwflZBMd60IHuWDlr:-MzxmjPZ1CxCbbbB-yGw:bj05gvs) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Who uses iPhone 12 in landscape? :laughing: My proposition:
* Currently we have 128px margin on top and 64px at the bottom and align the dialog towards the top.
* Instead we center the dialog vertically with a margin of 10% at both top and bottom..
</blockquote></details>

Yeah sounds good! I'd prefer not to make any assumptions about how people use it. 

---
___
*[src/components/SelectField/baseTheme.jsx, line 145 at r3](https://reviewable.io/reviews/qualifyze/design-system/284#-MzxmzAS7Q9VmI1fKvRj:-MzxmzAS7Q9VmI1fKvRk:bxxaa4u) ([raw file](https://github.com/qualifyze/design-system/blob/96efb2a1802ca2d363e8c6d7cf077f740a06fad3/src/components/SelectField/baseTheme.jsx#L145)):*
> ```JavaScript
>   menuPortal: provided => ({
>     ...provided,
>     zIndex: 9999,
> ```

Wait do we really need this? I'd recommend staying away from z-index as much as possible because it leads to weird bugs. Could we not expose the `menuPortalTarget` and let the DOM do its thing?

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[src/components/SelectField/baseTheme.jsx, line 145 at r3](https://reviewable.io/reviews/qualifyze/design-system/284#-MzxmzAS7Q9VmI1fKvRj:-MzxpeBz9nBC8QYTnZCO:b-zhhait) ([raw file](https://github.com/qualifyze/design-system/blob/96efb2a1802ca2d363e8c6d7cf077f740a06fad3/src/components/SelectField/baseTheme.jsx#L145)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Wait do we really need this? I'd recommend staying away from z-index as much as possible because it leads to weird bugs. Could we not expose the `menuPortalTarget` and let the DOM do its thing?
</blockquote></details>

I'm just now realizing this doesn't only affect select but all components inside the modal body, right? If that's correct than I don't really feel comfortable shipping it like this, because it should't be difficult to have things sticking out of the modal.

**Comment by pablosci** [comment]
@phjardas didn't saw an answer for this, just a reminder: now all actions are going to be inline instead of fixed on side?

**Review by pablosci — CHANGES_REQUESTED** [review]
"The actions of the sidebar are now always at the bottom of the screen."
On the preview link there are always inline at the bottom of the content, not the side.

"On small screens all dialogs are now displayed full-screen."
On the preview link modal is being displayed at the bottom with a lot of empty space on top:
Screenshot 2022-04-06 at 14 39 26

"Better scrolling behavior for long content: the header and actions now stay fixed and only the content scrolls."
On preview with a modal with long content the actions actually are moved with the scroll content.
Screenshot 2022-04-06 at 14 41 18

If this was corrected avoid the comment.

**Review by phjardas — COMMENTED** [review]
I've implemented all of these changes after comments in this PR.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284#-:-N-77-tT9VzxFgGzUjHF:bl4lotx)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[src/components/SelectField/baseTheme.jsx, line 145 at r3](https://reviewable.io/reviews/qualifyze/design-system/284#-MzxmzAS7Q9VmI1fKvRj:-N-77BaG0SFp-K2oQS7n:b-t2xna4) ([raw file](https://github.com/qualifyze/design-system/blob/96efb2a1802ca2d363e8c6d7cf077f740a06fad3/src/components/SelectField/baseTheme.jsx#L145)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I'm just now realizing this doesn't only affect select but all components inside the modal body, right? If that's correct than I don't really feel comfortable shipping it like this, because it should't be difficult to have things sticking out of the modal. 
</blockquote></details>

No this only affects the select component. But it does affect all select components, not only those inside a modal. I've run some tests and couldn't see any difference in behavior or layout for selects outside of modals. The z-index is necessary for portalled components because they by definition don't inherit the z-index of their "containing" element.

**Review by pablosci — CHANGES_REQUESTED** [review]
Everything is working ok, but for the next one:
"The actions of the sidebar are now always at the bottom of the screen."
On the preview link there are always inline at the bottom of the content, not at the bottom of the side, not having the action on sight can be tricky

**Comment by gregoralbrecht** [comment]
> Everything is working ok, but for the next one: "The actions of the sidebar are now always at the bottom of the screen." On the preview link there are always inline at the bottom of the content, not at the bottom of the side, not having the action on sight can be tricky

@pablosci I disagree. IMO, seeing an action without having seen all the content is more dangerous than having to scroll to see the action

**Comment by pablosci** [comment]
> > Everything is working ok, but for the next one: "The actions of the sidebar are now always at the bottom of the screen." On the preview link there are always inline at the bottom of the content, not at the bottom of the side, not having the action on sight can be tricky
> 
> @pablosci I disagree. IMO, seeing an action without having seen all the content is more dangerous than having to scroll to see the action

I get that, but I do also believe that not seeing how to successfully complete what I'm doing can be dangerous too, keep in mind this is going to be used to perform small / medium task in context and move on, so always having in hand a safe way to finish add it's value as sometimes they simply cannot see the main action. And also always be sure where this action is.
When we tested this solution I asked for this specific topic, and some users said that this actually enables them to reflect what they have done and confirm it.
We can introduce this chance and collect some feedback, it doesn't hurt as right now is implemented in few places.

**Review by gregoralbrecht — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phjardas)

___
*[src/components/SelectField/baseTheme.jsx, line 145 at r3](https://reviewable.io/reviews/qualifyze/design-system/284#-MzxmzAS7Q9VmI1fKvRj:-N-Y1l8I1kltY5HWSRNb:bvyp5p4) ([raw file](https://github.com/qualifyze/design-system/blob/96efb2a1802ca2d363e8c6d7cf077f740a06fad3/src/components/SelectField/baseTheme.jsx#L145)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

No this only affects the select component. But it does affect all select components, not only those inside a modal. I've run some tests and couldn't see any difference in behavior or layout for selects outside of modals. The z-index is necessary for portalled components because they by definition don't inherit the z-index of their "containing" element.
</blockquote></details>

I don't understand why it would only affect `Select` but not other components inside `Modal.Content` that render something that might stick out? I thought the fixed header was blocking it? Haven't tried it, but if you say it's not a problem, let's merge.

I really dislike seeing a specific `z-index` there is probably a cleaner solution that doesn't involve setting `z-index`.

**Review by gregoralbrecht — COMMENTED** [review]
> keep in mind this is going to be used to perform small / medium task in context and move on

We're talking about modals with a lot of content. These with little content won't be affected because the actions are visible either way (with the changes in this PR and without). I don't see how there would be a modal with much content where the actions aren't visible?

I still believe if there is text in the modal's body and it's important that people read it, then having the actions right available right there is dangerous. Especially with the design proposed in this PR, it's not obvious at all that there might be more context that I, as a user, might want to read.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284#-:-N-YUiur2g9MR2hNbcO9:b-90x1r9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phjardas)

**Review by gregoralbrecht — COMMENTED** [review]
Look at this screenshot posted earlier. There is content below "artichoke" and I don't think that's obvious. 


> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284#-:-N-YXb-97zKZCQo5E9fx:bsbtlli)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phjardas)

**Review by phjardas — COMMENTED** [review]
@jordi-castillo as discussed I've again fixed the buttons at the bottom of the dialog/sidebar and let only the content scroll. When there's scrollable content at either the top or the bottom of the content, we now display a little drop shadow as an indicator.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284#-:-N0_H9uz8Ju-obWe99Uy:b-u04e8w)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @gregoralbrecht)

**Review by Jordi-Castillo — APPROVED** [review]
Looks good to me, only if you could use this parameters for the shadow:
box-shadow: 0px 0px 32px rgba(0, 0, 0, 0.12);

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @phjardas)

___
*[`src/components/Actions/index.jsx` line 7 at r1](https://reviewable.io/reviews/qualifyze/design-system/284#-N0_iYMA5rMD2OENykMy:-N0_iYMA5rMD2OENykMz:bpsd9ew) ([raw file](https://github.com/qualifyze/design-system/blob/b1c316f4e17c900f34f54bb99042708df02cbe36/src/components/Actions/index.jsx#L7)):*
> ```JavaScript
> import ActionsContext from './ActionsContext'
> 
> // We need the `.actions` class just to make sure we don't break old designs.
> ```

Thanks for cleaning up!
___
*[`src/components/Modal/index.jsx` line 54 at r5](https://reviewable.io/reviews/qualifyze/design-system/284#-N0_iSxq2qTBeTJVkdB3:-N0_iSxq2qTBeTJVkdB4:b8jmpfm) ([raw file](https://github.com/qualifyze/design-system/blob/a59b7e7a49181fa08148a6e84e0757e1e4bd4215/src/components/Modal/index.jsx#L54)):*
> ```JavaScript
>           'linear-gradient(white 30%, rgba(255, 255, 255, 0)) center top',
>           'linear-gradient(rgba(255, 255, 255, 0), white 70%) center bottom',
>           // 'radial-gradient(farthest-side at 50% 0,rgba(0, 0, 0, 0.2),rgba(0, 0, 0, 0)) center top',
> ```

Can we remove this?

**Comment by phjardas** [comment]
> Looks good to me, only if you could use this parameters for the shadow: box-shadow: 0px 0px 32px rgba(0, 0, 0, 0.12);

@Jordi-Castillo I can't because the shadow is created with a linear gradient background, not with a drop shadow. I tried to stay as close as possible to the figma template, but it's impossible to convert one into the other numerically.

**Review by phjardas — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r3, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[`src/components/Modal/index.jsx` line 54 at r5](https://reviewable.io/reviews/qualifyze/design-system/284#-N0_iSxq2qTBeTJVkdB3:-N0aEyPgE1010NfcaH5p:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/a59b7e7a49181fa08148a6e84e0757e1e4bd4215/src/components/Modal/index.jsx#L54)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Can we remove this?
</blockquote></details>

Done.

**Review by phjardas — COMMENTED** [review]
> Dismissed @gregoralbrecht from a discussion.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregoralbrecht)

**Pull request merged**
