### PR TITLE
Use react version of airbnb eslint rules

### PR DESCRIPTION
**Pull request by vubogovich**
## What

Use react version of airbnb eslint rules.

## Why

They help to avoid common mistakes working with react components.
Looking at the disabled rules in some files it looks like those rules were there at some point, probably replaced when extracted from the monorepo.

## Who is affected

No functional changes are expected but will release a patch due to new default value for `MultiSelectAsyncCreatableField`.

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/170)

### CODE REVIEW

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
Great catch! Let's use the non-`base` version, makes sense. Personally, I don't see the value of defining undefined default props at all, though. We've been disabling the eslint warnings on prop-types more and more lately, just because we're slowly moving away from prop-types towards default function parameters. Without Typescript this not the most pleasurable of experiences because there's no substitute for prop-types linting.

Bottom line: In this non-TS project, there's no great alternative to linting prop-types but I do believe the value this brings is rather debatable in most cases. Hence, we disabled the rule quite often where necessary. I don't see the value in undefined default props but if you want to use it then feel free to go ahead.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/170#-:-Mhnw8kmDI8V5Bae0E9f:b-deitz)* status: all files reviewed, 1 unresolved discussion (waiting on @vubogovich)

___
*[.changeset/rotten-worms-glow.md, line 5 at r1](https://reviewable.io/reviews/qualifyze/design-system/170#-Mhnwzwe9WnV1VdA4H_I:-Mhnwzwe9WnV1VdA4H_J:bs2zdvj) ([raw file](https://github.com/qualifyze/design-system/blob/5ea188c40ade959b9cbffb934cce641bbd65728f/.changeset/rotten-worms-glow.md#L5)):*
> ```Markdown
> ---
> 
> Update default props of select components to be compliant with more strict eslint rules.
> ```

If I'm not missing anything, nothing changed in terms of functionality so what's the reason for a version bump?

**Review by vubogovich — COMMENTED** [review]
In addition to https://github.com/airbnb/javascript/tree/master/react#props

> propTypes are a form of documentation, and providing defaultProps means the reader of your code doesn’t have to assume as much. In addition, it can mean that your code can omit certain type checks.

I can say that defaultProps is a safer way to default the complex objects (array, object, arrow function) to avoid re-rendering. Checking how default values for props in the render method are transpiled (see /dist/components/MultiSelectAsyncCreatableField/index.js in the main branch), they surprisingly go to `defaultProps` but eslint does not notice it and still complain. If I were to choose where to put default definitions, it would be very close to the propType of the corresponding field.

It does not make sense to ignore prop-by-prop instead of adding `undefined` to default props. If the rule is not welcome, better to disable it for the whole package and remove the noisy eslint exceptions. But this can be safely another PR as the current one is good to go on its own.

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/170#-:-Mhp8zIJ5aqCfZNezhDi:boiz6do)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[.changeset/rotten-worms-glow.md, line 5 at r1](https://reviewable.io/reviews/qualifyze/design-system/170#-Mhnwzwe9WnV1VdA4H_I:-MhpByqbE-f9JmHXUiz4:b-iwlhc1) ([raw file](https://github.com/qualifyze/design-system/blob/5ea188c40ade959b9cbffb934cce641bbd65728f/.changeset/rotten-worms-glow.md#L5)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

If I'm not missing anything, nothing changed in terms of functionality so what's the reason for a version bump?
</blockquote></details>

I thought moving default value from function argument to `defaultProps` is a tiny change but actually it gets transpiled to the same result, so indeed no functional change at all.

**Review by gregoralbrecht — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/170)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @gregoralbrecht)

**Review by vubogovich — COMMENTED** [review]
> Reviewed 7 of 12 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @vubogovich)

**Pull request merged**
