### PR TITLE
Add primary tone for `Icon`

### PR DESCRIPTION
**Pull request by vubogovich**
Needed for the lock icon according to Figma in Qualifyze/audit-ui#12

### CODE REVIEW

**Comment by gsuess** [comment]
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/319)

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
I feel like we should avoid using "primary" icons because I'm struggling to see the semantic meaning behind them. Granted, "secondary" isn't great, either. What's the intention here?

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/319#-:-N2LDwvODRl63hbRBTib:b133tec)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @vubogovich)

**Review by vubogovich — COMMENTED** [review]
Sorry for the missing context - please check Figma linked in the related PR Qualifyze/audit-ui#12

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/319#-:-N2LclIH7X1yq07JziBZ:b-a5dp3p)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @vubogovich)

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
No worries :) I'm not convinced we need another tone yet if it's just one occurrence of another color. I feel like the PR you linked looks fine :)

> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/319#-:-N2LdGCX3uZStSk_84tA:b-u6q4sw)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @vubogovich)

**Comment by vubogovich** [comment]
Ok, closing until the second occurrence.

**Pull request closed without merging**
