### PR TITLE
Reduce usage of secondary color across many components (DI-63)

### PR DESCRIPTION
**Pull request by phjardas**
Replace secondary with primary color in the following components:

* `AutosuggestField`
* `FieldLabel`
* `FileUpload` -- icon color
* `Icon` -- tone `info`
* `SelectField` -- hover background
* `Text` -- tone `info`

Replace secondary color with gray in the following components:

* `Heading`

The rest of the changes only affects the Storybook stories.

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/222)

### CODE REVIEW

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
Thank you for the PR! :clap: 

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/222#-:-MoJPFxk4C-iKvZ62u_3:blzmnud)* status: all files reviewed, 3 unresolved discussions (waiting on @phjardas)

___
*[src/components/FieldLabel/index.jsx, line 44 at r1](https://reviewable.io/reviews/qualifyze/design-system/222#-MoJO0gh4y4VczkK78f6:-MoJO0gh4y4VczkK78f7:b-u41tk9) ([raw file](https://github.com/qualifyze/design-system/blob/685570aae5b43064cc4093f63741c636ab8099d6/src/components/FieldLabel/index.jsx#L44)):*
> ```JavaScript
>       {description ? (
>         <Box>
>           <Text tone="primary">{description}</Text>
> ```

Search and replace mishap?
___
*[src/components/Heading/index.jsx, line 79 at r1](https://reviewable.io/reviews/qualifyze/design-system/222#-MoJOJRm9XPKFftdudGc:-MoJOJRm9XPKFftdudGd:bmi8ppe) ([raw file](https://github.com/qualifyze/design-system/blob/685570aae5b43064cc4093f63741c636ab8099d6/src/components/Heading/index.jsx#L79)):*
> ```JavaScript
>   level: 1,
>   weight: 'regular',
>   color: 'grey.800',
> ```

:100: 
___
*[src/components/Icon/index.jsx, line 69 at r1](https://reviewable.io/reviews/qualifyze/design-system/222#-MoJOUyL-1UB2pOESEdd:-MoJOUyL-1UB2pOESEde:b3c11f8) ([raw file](https://github.com/qualifyze/design-system/blob/685570aae5b43064cc4093f63741c636ab8099d6/src/components/Icon/index.jsx#L69)):*
> ```JavaScript
>       },
>       info: {
>         color: 'primary.600',
> ```

Makes sense :+1: 
___
*[src/components/Text/index.jsx, line 71 at r1](https://reviewable.io/reviews/qualifyze/design-system/222#-MoJOq17DsqvOg2jy1HR:-MoJOq17DsqvOg2jy1HS:bu07417) ([raw file](https://github.com/qualifyze/design-system/blob/685570aae5b43064cc4093f63741c636ab8099d6/src/components/Text/index.jsx#L71)):*
> ```JavaScript
>       },
>       info: {
>         color: 'primary.600',
> ```

Personally not a fan of this because—as I've mentioned in the initiative—primary should carry some kind of notion of "interactive". This is the opposite, it's "informative". I don't feel strongly about it, though. cc @pablosci 
___
*[src/playground/LogoCloud/index.stories.jsx, line 21 at r1](https://reviewable.io/reviews/qualifyze/design-system/222#-MoJP91y8wiT_Q5DKn3Q:-MoJP91y8wiT_Q5DKn3R:b-u41tk9) ([raw file](https://github.com/qualifyze/design-system/blob/685570aae5b43064cc4093f63741c636ab8099d6/src/playground/LogoCloud/index.stories.jsx#L21)):*
> ```JavaScript
>     <Box sx={{ px: [3, 4, 5], py: [4, 5, 6], bg: 'background.0' }}>
>       <Stack space={3}>
>         <Text as="h2" weight="medium" tone="primary" align="center">
> ```

Search and replace mishap?

**Comment by phjardas** [comment]
This change makes even more sense considering that our new secondary color is going to be pink. :-)

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/222)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @gregoralbrecht, @pablosci, and @phjardas)

___
*[`src/components/Text/index.jsx` line 71 at r1](https://reviewable.io/reviews/qualifyze/design-system/222#-MoJOq17DsqvOg2jy1HR:-N2RGgzM57ktEMFjZmUe:b3rpwrz) ([raw file](https://github.com/qualifyze/design-system/blob/685570aae5b43064cc4093f63741c636ab8099d6/src/components/Text/index.jsx#L71)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Personally not a fan of this because—as I've mentioned in the initiative—primary should carry some kind of notion of "interactive". This is the opposite, it's "informative". I don't feel strongly about it, though. cc @pablosci 
</blockquote></details>

Well, we don't really have a color for info, do we?
___
*[`src/playground/LogoCloud/index.stories.jsx` line 21 at r1](https://reviewable.io/reviews/qualifyze/design-system/222#-MoJP91y8wiT_Q5DKn3Q:-N2RHEi55Jn_P00bLeOe:bt2vr1b) ([raw file](https://github.com/qualifyze/design-system/blob/685570aae5b43064cc4093f63741c636ab8099d6/src/playground/LogoCloud/index.stories.jsx#L21)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Search and replace mishap?
</blockquote></details>

Fixed.

**Review by gregoralbrecht — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/222)* status: all files reviewed, 1 unresolved discussion (waiting on @pablosci)

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/222)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @gregoralbrecht and @pablosci)

___
*[`src/components/FieldLabel/index.jsx` line 44 at r1](https://reviewable.io/reviews/qualifyze/design-system/222#-MoJO0gh4y4VczkK78f6:-N2Rafaa5AwzGN3HDhzg:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/685570aae5b43064cc4093f63741c636ab8099d6/src/components/FieldLabel/index.jsx#L44)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Search and replace mishap?
</blockquote></details>

Done.

**Review by phjardas — COMMENTED** [review]
> Reviewed 10 of 14 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/222)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @gregoralbrecht, @pablosci, and @phjardas)

**Review by phjardas — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/222)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregoralbrecht and @pablosci)

**Pull request merged**
