### PR TITLE
Migrate dropdown menu to use Reach instead of Radix (QC-2017)

### PR DESCRIPTION
**Pull request by phjardas**
The library component from Radix UI does not support IE11 which breaks
the app on IE11. In this PR we replace Radix with Reach, however we're
breaking some functionality with it, especially the `asChild` attribute
and having to remove the functionality of nested menus. The component is
only used in two well-known places, so we're going with a minor release.

### CODE REVIEW

**Comment by gsuess** [comment]
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
Thank you for the PR! :trophy: Code looks great! Just a nitpick on a11y and a short discussion on the breaking changes from my side :) 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318#-:-N2B7tZO5lmidAiVISON:b4gutdi)* status: all files reviewed, 2 unresolved discussions (waiting on @phjardas)

___
*[`.changeset/itchy-trains-ring.md` line 2 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8-mmDQPo_NVm3WMd:-N2B8-mmDQPo_NVm3WMe:b4ru6sm) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/.changeset/itchy-trains-ring.md#L2)):*
> ```Markdown
> ---
> '@qualifyze/design-system': minor
> ```

I believe we should make this a new major version because it's a breaking change. However, could we not make `Trigger` a bit smarter and basically take `props.children` and put it into the `as` prop internally? I might be missing something, though?
___
*[`src/components/DropdownMenu/index.jsx` line 42 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8Va9-Zkkt0NyCS72:-N2B8Va9-Zkkt0NyCS73:b-1nvgln) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/src/components/DropdownMenu/index.jsx#L42)):*
> ```JavaScript
>   },
> 
>   '&:hover': {
> ```

Wait — where were the previous hover styles coming from? :eyes: :sweat_smile: 
___
*[`src/components/DropdownMenu/index.jsx` line 56 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8uYi5HrODL4mzqXb:-N2B8uYj3LBfQkOJswhJ:b-qweliq) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/src/components/DropdownMenu/index.jsx#L56)):*
> ```JavaScript
> )
> 
> const StyledSeparator = styled.div(props => ({
> ```

In Radix, this is a `<div role="separator" aria-orientation="horizontal"></div>` maybe we can just adopt this?

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: all files reviewed, 3 unresolved discussions (waiting on @phjardas)

___
*[`src/components/DropdownMenu/index.stories.jsx` line 27 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BB528EDdvoVwSIXVv:-N2BB528EDdvoVwSIXVw:b-60x5v6) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/src/components/DropdownMenu/index.stories.jsx#L27)):*
> ```JavaScript
> export default { title: 'DropdownMenu', component: DropdownMenu }
> 
> export const Default = () => {
> ```

Can we include a story on how to do nested menus?

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: all files reviewed, 4 unresolved discussions (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BBcwYATGEF_FqzuZb:-N2BBcwYATGEF_FqzuZc:bh0moxn) (no related file):*
There seems to be a border that's being toggled when you click the `Trigger` repeatedly:
[Kapture 2022-05-16 at 11.27.44.mp4](https://files.reviewableusercontent.io/images/reviewable/6179211/ZpOY0n2q4vVTUWleW6iDZVq2/Kapture%202022-05-16%20at%2011.27.44.mp4)

___

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: all files reviewed, 5 unresolved discussions (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BCVRG18TJRyzZH40r:-N2BCVRH1KsVgYDhmpQc:bivb63d) (no related file):*
The changes break keyboard navigation but I'm not sure why yet. 

1. Focus the `Trigger` and click Enter or Space
2. Dropdown opens but the whole thing is in focus instead of a menu item

Currently:


In this PR:


___

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: all files reviewed, 5 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

___
*[`src/components/DropdownMenu/index.stories.jsx` line 27 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BB528EDdvoVwSIXVv:-N2BRFHo9s3xItBjgehG:be3w8f) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/src/components/DropdownMenu/index.stories.jsx#L27)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Can we include a story on how to do nested menus? 
</blockquote></details>

There is no support for nested menues in Reach. :-(

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: all files reviewed, 5 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BCVRG18TJRyzZH40r:-N2BXMGQ3Q-h042XUcrU:b-fq1svt) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The changes break keyboard navigation but I'm not sure why yet. 

1. Focus the `Trigger` and click Enter or Space
2. Dropdown opens but the whole thing is in focus instead of a menu item

Currently:


In this PR:


</blockquote></details>

Keyboard navigation is not broken, the correct elements are focused on tabbing. It's just the styles that are misleading. The container has a border on `focus-within`, and the individual elements don't have `focus` styles.

___
___
*[`.changeset/itchy-trains-ring.md` line 2 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8-mmDQPo_NVm3WMd:-N2BWelTDwTqjl1xCb7R:b-6wkvoy) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/.changeset/itchy-trains-ring.md#L2)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I believe we should make this a new major version because it's a breaking change. However, could we not make `Trigger` a bit smarter and basically take `props.children` and put it into the `as` prop internally? I might be missing something, though?
</blockquote></details>

This will not work at all if `children` is an array. :-(

Updated the change to `major`.
___
*[`src/components/DropdownMenu/index.jsx` line 42 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8Va9-Zkkt0NyCS72:-N2BWmmr189INOxi66ax:b-hnqg1u) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/src/components/DropdownMenu/index.jsx#L42)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Wait — where were the previous hover styles coming from? :eyes: :sweat_smile: 
</blockquote></details>

I have no idea. :see_no_evil: 
___
*[`src/components/DropdownMenu/index.jsx` line 56 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8uYi5HrODL4mzqXb:-N2BWoSG8GkNWQdten2o:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/src/components/DropdownMenu/index.jsx#L56)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

In Radix, this is a `<div role="separator" aria-orientation="horizontal"></div>` maybe we can just adopt this?
</blockquote></details>

Done.

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BCVRG18TJRyzZH40r:-N2CAxpN7ttkMonHImMh:b-lmpwmq) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Keyboard navigation is not broken, the correct elements are focused on tabbing. It's just the styles that are misleading. The container has a border on `focus-within`, and the individual elements don't have `focus` styles.
</blockquote></details>

Gotcha! Sorry for the confusion. Then let's remove the `focus-within` styles and use the focus ring for the items' focus styles

___
___
*[`.changeset/itchy-trains-ring.md` line 2 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8-mmDQPo_NVm3WMd:-N2CB9u_DSNSXitLOzx0:b-eqjvg) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/.changeset/itchy-trains-ring.md#L2)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

This will not work at all if `children` is an array. :-(

Updated the change to `major`.
</blockquote></details>

This is fine as long as we're explicit (i.e. prop types) about it, right? I can see how it would be confusing, though. I don't have a strong opinion either way.
___
*[`src/components/DropdownMenu/index.jsx` line 42 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8Va9-Zkkt0NyCS72:-N2CBTkq1AcjhdbQ3g6w:bi4dmar) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/src/components/DropdownMenu/index.jsx#L42)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

I have no idea. :see_no_evil: 
</blockquote></details>

Interesting :thinking:

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BBcwYATGEF_FqzuZb:-N2GE6RA4ekt10Ob4qQZ:b-ue9tc9) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

There seems to be a border that's being toggled when you click the `Trigger` repeatedly:
[Kapture 2022-05-16 at 11.27.44.mp4](https://files.reviewableusercontent.io/images/reviewable/6179211/ZpOY0n2q4vVTUWleW6iDZVq2/Kapture%202022-05-16%20at%2011.27.44.mp4)

</blockquote></details>

This behavior comes from the styles

```
*:focus:not(:focus-visible) {
    outline: none !important;
    box-shadow: none !important;
    border: none !important;
}
```

When you close the menu by pressing the button, it regains focus. But since the action was performed through a mouse interaction, the focus should not be visible, hence: `border: none !important` which I find a very peculiar style to be honest.

___

**Review by gregoralbrecht — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: all files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

___
*[`src/components/DropdownMenu/index.stories.jsx` line 27 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BB528EDdvoVwSIXVv:-N2Q9z70D1keXUbFVIek:bksuzot) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/src/components/DropdownMenu/index.stories.jsx#L27)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

There is no support for nested menues in Reach. :-(
</blockquote></details>

Got it, not a blocker IMHO let's just mention it in the release notes

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: all files reviewed, 2 unresolved discussions (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BBcwYATGEF_FqzuZb:-N2QA6MF5K6j1ejCTVvv:b-c8ugdn) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

This behavior comes from the styles

```
*:focus:not(:focus-visible) {
    outline: none !important;
    box-shadow: none !important;
    border: none !important;
}
```

When you close the menu by pressing the button, it regains focus. But since the action was performed through a mouse interaction, the focus should not be visible, hence: `border: none !important` which I find a very peculiar style to be honest.
</blockquote></details>

My bad, I didn't look at the code. I believe the story is at fault here, not the component itself. We can remove the border on the button in the story.

___

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BBcwYATGEF_FqzuZb:-N2RFieM65cHh9GbEpiH:b-896fix) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

My bad, I didn't look at the code. I believe the story is at fault here, not the component itself. We can remove the border on the button in the story.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BCVRG18TJRyzZH40r:-N2RFk-p-KBx52cNt8Nw:b7qjtrj) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Gotcha! Sorry for the confusion. Then let's remove the `focus-within` styles and use the focus ring for the items' focus styles
</blockquote></details>

We'd like to release this component even with the known issue around focus management when using keyboard navigation. I've added a notice to the release notes. Would you be okay with this @gregoralbrecht ?

___
___
*[`.changeset/itchy-trains-ring.md` line 2 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8-mmDQPo_NVm3WMd:-N2RFvvm-DOaivRi036h:b-9z2039) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/.changeset/itchy-trains-ring.md#L2)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

This is fine as long as we're explicit (i.e. prop types) about it, right? I can see how it would be confusing, though. I don't have a strong opinion either way.
</blockquote></details>

Then let's use the non-compatible way, because I'll have to update all consumers of this component anyway. 
___
*[`src/components/DropdownMenu/index.stories.jsx` line 27 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BB528EDdvoVwSIXVv:-N2RG1x51Q9JAXIHKpIQ:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/src/components/DropdownMenu/index.stories.jsx#L27)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Got it, not a blocker IMHO let's just mention it in the release notes
</blockquote></details>

Done.

**Review by gregoralbrecht — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BCVRG18TJRyzZH40r:-N2RHr197joZ2A6MXJmP:b2aarir) (no related file):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

We'd like to release this component even with the known issue around focus management when using keyboard navigation. I've added a notice to the release notes. Would you be okay with this @gregoralbrecht ?
</blockquote></details>

Actually, no. But I won't stop you.

___
___
*[`.changeset/itchy-trains-ring.md` line 2 at r1](https://reviewable.io/reviews/qualifyze/design-system/318#-N2B8-mmDQPo_NVm3WMd:-N2RI00h1lBd4NIMmGrp:bb73djm) ([raw file](https://github.com/qualifyze/design-system/blob/a7315e5b478f1f5747ee16f9cc24ec6a79b68522/.changeset/itchy-trains-ring.md#L2)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Then let's use the non-compatible way, because I'll have to update all consumers of this component anyway. 
</blockquote></details>

SGTM

**Review by phjardas — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> Dismissed @gregoralbrecht from a discussion.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/318)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @phjardas)

*[a discussion](https://reviewable.io/reviews/qualifyze/design-system/318#-N2BCVRG18TJRyzZH40r:-N2RP4Cs0dj3fEqu_PEo:b-896fix) (no related file):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Actually, no. But I won't stop you.
</blockquote></details>

Done.

___

**Pull request merged**
