### PR TITLE
Logo: allow string values for width and height

### PR DESCRIPTION
**Pull request by phjardas**
This change allows property values like "100%" or "auto".

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)

### CODE REVIEW

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[src/components/Logo/index.jsx, line 11 at r1](https://reviewable.io/reviews/qualifyze/design-system/189#-Mkbkxx_65TAOJ5Mvnld:-Mkbkxx_65TAOJ5Mvnle:b-ftbzji) ([raw file](https://github.com/qualifyze/design-system/blob/4adc2b728f89d4224b082f48f7eaef36d036cc09/src/components/Logo/index.jsx#L11)):*
> ```JavaScript
> 
>   return (
>     <svg viewBox="0 0 415 100" fill="none" {...props}>
> ```

Instead of spreading all props, let's remove `{...props}` and keep `width` and `height` explicitly

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[src/components/Logo/index.jsx, line 11 at r1](https://reviewable.io/reviews/qualifyze/design-system/189#-Mkbkxx_65TAOJ5Mvnld:-MkblGmy8UHHd6Ong8E7:bb6h2if) ([raw file](https://github.com/qualifyze/design-system/blob/4adc2b728f89d4224b082f48f7eaef36d036cc09/src/components/Logo/index.jsx#L11)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Instead of spreading all props, let's remove `{...props}` and keep `width` and `height` explicitly
</blockquote></details>

Why tho? Spreading the props is a lot more compatible. This way one could also pass `className` and `style` and `aria-*` and `data-*` properties.

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[src/components/Logo/index.jsx, line 11 at r1](https://reviewable.io/reviews/qualifyze/design-system/189#-Mkbkxx_65TAOJ5Mvnld:-Mkbl_DD3Ve3cQay_JY-:b50tjsl) ([raw file](https://github.com/qualifyze/design-system/blob/4adc2b728f89d4224b082f48f7eaef36d036cc09/src/components/Logo/index.jsx#L11)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Why tho? Spreading the props is a lot more compatible. This way one could also pass `className` and `style` and `aria-*` and `data-*` properties.
</blockquote></details>

Prop spreading blows up the API of each component unnecessarily. For logo, this might even be fine but for more complex components this makes it impossible refactor later because consumers might rely on DOM structures you want to change. If you want a component to support `className`, we should pass it explicitly, same with `style`

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[src/components/Logo/index.jsx, line 11 at r1](https://reviewable.io/reviews/qualifyze/design-system/189#-Mkbkxx_65TAOJ5Mvnld:-MkbmAGkDV7NEuo3SzCz:bcy4wi) ([raw file](https://github.com/qualifyze/design-system/blob/4adc2b728f89d4224b082f48f7eaef36d036cc09/src/components/Logo/index.jsx#L11)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Prop spreading blows up the API of each component unnecessarily. For logo, this might even be fine but for more complex components this makes it impossible refactor later because consumers might rely on DOM structures you want to change. If you want a component to support `className`, we should pass it explicitly, same with `style`
</blockquote></details>

How would you allow to pass all the `aria-*` and arbitrary `data-*` properties?

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[src/components/Logo/index.jsx, line 11 at r1](https://reviewable.io/reviews/qualifyze/design-system/189#-Mkbkxx_65TAOJ5Mvnld:-MkbmWm6Ci4Pu3X8V-Sq:b-y0dcvc) ([raw file](https://github.com/qualifyze/design-system/blob/4adc2b728f89d4224b082f48f7eaef36d036cc09/src/components/Logo/index.jsx#L11)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

How would you allow to pass all the `aria-*` and arbitrary `data-*` properties?
</blockquote></details>

By creating an explicit API for it, e.g. by passing `ariaAttribute` or whatever you'd want to do

**Review by gregoralbrecht — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: all files reviewed, 1 unresolved discussion (waiting on @phjardas)

___
*[src/components/Logo/index.jsx, line 11 at r1](https://reviewable.io/reviews/qualifyze/design-system/189#-Mkbkxx_65TAOJ5Mvnld:-MkbmhU_2uEO5K6lvOXW:b1gvejk) ([raw file](https://github.com/qualifyze/design-system/blob/4adc2b728f89d4224b082f48f7eaef36d036cc09/src/components/Logo/index.jsx#L11)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

By creating an explicit API for it, e.g. by passing `ariaAttribute` or whatever you'd want to do
</blockquote></details>

The broader the API surface, the harder it is to make changes in the DS. Prop spreading = veeery big API surface

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[src/components/Logo/index.jsx, line 11 at r1](https://reviewable.io/reviews/qualifyze/design-system/189#-Mkbkxx_65TAOJ5Mvnld:-Mkbn4M65pLyjosuEWM9:b-t4ov2r) ([raw file](https://github.com/qualifyze/design-system/blob/4adc2b728f89d4224b082f48f7eaef36d036cc09/src/components/Logo/index.jsx#L11)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

The broader the API surface, the harder it is to make changes in the DS. Prop spreading = veeery big API surface
</blockquote></details>

From my experience the added flexibility is worth a lot more. I've had bad experience with too restrictive design systems in the past.

**Review by gregoralbrecht — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht and @phjardas)

___
*[src/components/Logo/index.jsx, line 11 at r1](https://reviewable.io/reviews/qualifyze/design-system/189#-Mkbkxx_65TAOJ5Mvnld:-MkbnoeZ5Q62hZwj4KQl:bkhf3dt) ([raw file](https://github.com/qualifyze/design-system/blob/4adc2b728f89d4224b082f48f7eaef36d036cc09/src/components/Logo/index.jsx#L11)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

From my experience the added flexibility is worth a lot more. I've had bad experience with too restrictive design systems in the past.
</blockquote></details>

I'm aware it's a balance. I made the opposite experience with this very DS here

**Review by phjardas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[src/components/Logo/index.jsx, line 11 at r1](https://reviewable.io/reviews/qualifyze/design-system/189#-Mkbkxx_65TAOJ5Mvnld:-MmquhZr4UwX614WYbRo:b-896fix) ([raw file](https://github.com/qualifyze/design-system/blob/4adc2b728f89d4224b082f48f7eaef36d036cc09/src/components/Logo/index.jsx#L11)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

I'm aware it's a balance. I made the opposite experience with this very DS here
</blockquote></details>

Done.

**Review by phjardas — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

**Review by phjardas — COMMENTED** [review]
> Dismissed @gregoralbrecht from a discussion.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregoralbrecht)

**Pull request merged**
