### PR TITLE
Disable `TextLinkButton` when `isLoading` is true

### PR DESCRIPTION
**Pull request by gregoralbrecht**
We do this for `Button` so this aligns behaviors between the two.

---
This change is [Reviewable](https://reviewable.io/reviews/qualifyze/design-system/204)

### CODE REVIEW

**Review by phjardas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/204)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht)

___
*[src/components/TextLinkButton/index.jsx, line 9 at r1](https://reviewable.io/reviews/qualifyze/design-system/204#-Mlu9tAmBAajDynlh3ir:-Mlu9tAmBAajDynlh3is:b-yvp9uz) ([raw file](https://github.com/qualifyze/design-system/blob/f762dc0a21765d2c6fefb4c7ee70e015873c01cc/src/components/TextLinkButton/index.jsx#L9)):*
> ```JavaScript
>   const handleKeyPress = React.useCallback(
>     event => {
>       if ((!isLoading && event.code === 'Enter') || event.code === 'Space') {
> ```

I think the boolean grouping is wrong. You want to put brackets around the event codes instead.
___
*[src/components/TextLinkButton/index.jsx, line 21 at r1](https://reviewable.io/reviews/qualifyze/design-system/204#-MluA37N60QpRBvLGyb1:-MluA37N60QpRBvLGyb2:bvpo7l7) ([raw file](https://github.com/qualifyze/design-system/blob/f762dc0a21765d2c6fefb4c7ee70e015873c01cc/src/components/TextLinkButton/index.jsx#L21)):*
> ```JavaScript
>       role="button"
>       tabIndex={0}
>       onClick={isLoading ? undefined : onClick}
> ```

Not really necessary, you can keep the click handler static, because it checks for `isLoading` itself.

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/204)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

___
*[src/components/TextLinkButton/index.jsx, line 9 at r1](https://reviewable.io/reviews/qualifyze/design-system/204#-Mlu9tAmBAajDynlh3ir:-MluR-5M-PoHJr04xLHy:bcmu0dk) ([raw file](https://github.com/qualifyze/design-system/blob/f762dc0a21765d2c6fefb4c7ee70e015873c01cc/src/components/TextLinkButton/index.jsx#L9)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

I think the boolean grouping is wrong. You want to put brackets around the event codes instead.
</blockquote></details>

Should be good as it is and prettier doesn't like the parentheses and removes them :shrug: 
___
*[src/components/TextLinkButton/index.jsx, line 21 at r1](https://reviewable.io/reviews/qualifyze/design-system/204#-MluA37N60QpRBvLGyb1:-MluR3z56QBqZLUo2QJy:b-lm02iu) ([raw file](https://github.com/qualifyze/design-system/blob/f762dc0a21765d2c6fefb4c7ee70e015873c01cc/src/components/TextLinkButton/index.jsx#L21)):*
<details><summary><i>Previously, phjardas (Philipp Jardas) wrote…</i></summary><blockquote>

Not really necessary, you can keep the click handler static, because it checks for `isLoading` itself.
</blockquote></details>

How do you mean? What would check `isLoading`? `<TextLink>` doesn't do any checks because it's a link

**Review by gregoralbrecht — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/204)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @gregoralbrecht and @phjardas)

___
*[src/components/TextLinkButton/index.jsx, line 9 at r1](https://reviewable.io/reviews/qualifyze/design-system/204#-Mlu9tAmBAajDynlh3ir:-MluRWe_8qmKqy4OKoQC:bo8vmhm) ([raw file](https://github.com/qualifyze/design-system/blob/f762dc0a21765d2c6fefb4c7ee70e015873c01cc/src/components/TextLinkButton/index.jsx#L9)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

Should be good as it is and prettier doesn't like the parentheses and removes them :shrug: 
</blockquote></details>

I lied, sorry. Had a typo in this.

**Review by phjardas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/204)* status: all files reviewed, 1 unresolved discussion (waiting on @gregoralbrecht)

___
*[src/components/TextLinkButton/index.jsx, line 21 at r1](https://reviewable.io/reviews/qualifyze/design-system/204#-MluA37N60QpRBvLGyb1:-MmHQSxN9cdEzosg0lF9:b-6ulylb) ([raw file](https://github.com/qualifyze/design-system/blob/f762dc0a21765d2c6fefb4c7ee70e015873c01cc/src/components/TextLinkButton/index.jsx#L21)):*
<details><summary><i>Previously, gregoralbrecht (Gregor Albrecht) wrote…</i></summary><blockquote>

How do you mean? What would check `isLoading`? `<TextLink>` doesn't do any checks because it's a link
</blockquote></details>

Sorry, my bad. :see_no_evil:

**Review by phjardas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qualifyze/design-system/204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gregoralbrecht)

**Pull request merged**
